Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2018-10, with the labels that each got.

#71 Fix CCM container location in manifest
  manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#82 format log explicitly with Errorf() and Infof()
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/vclib/diskmanagers/vmdm.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#84 Add logo for helm chart
  docs/vmware_logo.png
Labels: approved, cncf-cla: yes, lgtm, size/XS

#85 Add empty CSI plugin
  .gitignore
  Gopkg.lock
  Gopkg.toml
  Makefile
  cmd/vsphere-csi/main.go
  pkg/csi/.gitkeep
  pkg/csi/provider/provider.go
  pkg/csi/service/controller.go
  pkg/csi/service/identity.go
  pkg/csi/service/node.go
  pkg/csi/service/service.go
Labels: approved, cncf-cla: yes, lgtm, size/L
