Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2018-07, with the labels that each got.

#12 Add refactoring design doc
  docs/refactor-design.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#16 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#14 Initial working CCM prototype
  Gopkg.lock
  Gopkg.toml
  cmd/vsphere-cloud-controller-manager/main.go
  manifests/controller-manager/README.md
  manifests/controller-manager/kubeadm.conf
  manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml
  manifests/controller-manager/vsphere.conf
  pkg/cloudprovider/providers/vsphere/.gitkeep
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/credentialmanager.go
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/types.go
  pkg/vclib/connection.go
  pkg/vclib/constants.go
  pkg/vclib/custom_errors.go
  pkg/vclib/datacenter.go
  pkg/vclib/datacenter_test.go
  pkg/vclib/datastore.go
  pkg/vclib/datastore_test.go
  pkg/vclib/diskmanagers/vdm.go
  pkg/vclib/diskmanagers/virtualdisk.go
  pkg/vclib/diskmanagers/vmdm.go
  pkg/vclib/folder.go
  pkg/vclib/folder_test.go
  pkg/vclib/pbm.go
  pkg/vclib/utils.go
  pkg/vclib/utils_test.go
  pkg/vclib/virtualmachine.go
  pkg/vclib/virtualmachine_test.go
  pkg/vclib/vmoptions.go
  pkg/vclib/volumeoptions.go
  pkg/vclib/vsphere_metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#20 RBAC for DS and Pod Deployment of CCM
  docs/deploying_cloud_provider_vsphere_with_rbac.md
  manifests/controller-manager/cloud-controller-manager-role-bindings.yaml
  manifests/controller-manager/cloud-controller-manager-roles.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#22 Allow using latest tag for docker push
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#25 docs: Update README with build tips
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#26 fix: Sets Makefile default target to "all: build"
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#27 Removing dead code
  pkg/cloudprovider/vsphere/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#28 Add documentation to Gopkg.toml
  Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#30 Updates for building the provider locally
  README.md
  hack/make.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
