Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2018-08, with the labels that each got.

#32 Adding code of conduct file
  code-of-conduct.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#33 Implement Kubernetes Secret for Storing vCenter Creds
  Gopkg.lock
  docs/deploying_cloud_provider_vsphere_with_rbac.md
  manifests/controller-manager/vccm-secret.yaml
  manifests/controller-manager/vsphere.conf
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/credentialmanager.go
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#39 Unit Test Coverage and Refactor Obtaining k8s Secret
  Gopkg.lock
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/credentialmanager.go
  pkg/cloudprovider/vsphere/credentialmanager_test.go
  pkg/cloudprovider/vsphere/types.go
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/vclib/connection.go
  pkg/vclib/connection_test.go
  pkg/vclib/fixtures/ca.key
  pkg/vclib/fixtures/ca.pem
  pkg/vclib/fixtures/createCerts.sh
  pkg/vclib/fixtures/fixtures.go
  pkg/vclib/fixtures/invalid.pem
  pkg/vclib/fixtures/server.csr
  pkg/vclib/fixtures/server.key
  pkg/vclib/fixtures/server.pem
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#31 Feature: Create vcpctl tool framework. (Stage 1)
  cmd/vcpctl/main.go
  cmd/vcpctl/provision/provision.go
  pkg/cli/cli.go
  pkg/cli/client.go
  pkg/cli/config.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#43 Implements NodeManager and Reconcile Based on UUID
  Gopkg.lock
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#42 Fix some grammatical errors to make the doc better
  docs/deploying_cloud_provider_vsphere_with_rbac.md
Labels: approved, cncf-cla: yes, lgtm, size/S
