Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2018-09, with the labels that each got.

#49 Documentation clarification for deploying CCM
  docs/deploying_cloud_provider_vsphere_with_rbac.md
Labels: cncf-cla: yes, size/XS

#45 Add NodeManager Unit Tests
  Gopkg.lock
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphere/vsphere_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#50 report node hostname
  pkg/cloudprovider/vsphere/nodemanager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#46 Feature: Create role and check vms on vSphere for enabling UUID (Stage 3 and 4)
  cmd/vcpctl/provision/provision.go
  pkg/cli/cli.go
  pkg/cli/user.go
  pkg/cli/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#54 Add doc for vcpctl
  docs/vcpctl.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#56 Expose gRPC call to obtain k8s VMs
  Gopkg.lock
  manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphere/proto/cloudprovidervsphere.pb.go
  pkg/cloudprovider/vsphere/proto/cloudprovidervsphere.proto
  pkg/cloudprovider/vsphere/server/server.go
  pkg/cloudprovider/vsphere/server/server_test.go
  pkg/cloudprovider/vsphere/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#58 Adds CCM user; fixes "watch secret" errors
  manifests/controller-manager/cloud-controller-manager-role-bindings.yaml
  manifests/controller-manager/cloud-controller-manager-roles.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#59 Fix insecure as true by default, pass flag to client option
  cmd/vcpctl/provision/provision.go
  pkg/cli/client.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#61 Support for building and pushing the CCM via Travis-CI
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#63 Disable k8s Secret Listener if Secret info is not provided.
  pkg/cloudprovider/vsphere/cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#66 Feature/k8s conformance
  .travis.yml
  e2e-job.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#67 General housekeeping/cleanup
  manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/credentialmanager.go
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/server/server.go
  pkg/cloudprovider/vsphere/server/server_test.go
  pkg/cloudprovider/vsphere/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#68 Fix for non-unique cluster names / disable PR builds in Travis-CI
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#69 Fix typos issue in vsphere_test.go
  pkg/cloudprovider/vsphere/vsphere_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#65 Add generating solution user key pair for login purpose
  pkg/cli/cli.go
  pkg/cli/user.go
Labels: approved, cncf-cla: yes, lgtm, size/M
