Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2018-12, with the labels that each got.

#109 Vendored BitBucket dependency
  vendor/bitbucket.org/ww/goautoneg/Makefile
  vendor/bitbucket.org/ww/goautoneg/README.txt
  vendor/bitbucket.org/ww/goautoneg/autoneg.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#111 Update to CSI 1.0.0 spec
  Gopkg.lock
  Gopkg.toml
  pkg/csi/service/fcd/controller.go
  pkg/csi/service/identity.go
  pkg/csi/service/node.go
  pkg/csi/service/service.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#113 update KEP link in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#110 Initial implementation for CSI create/delete
  Gopkg.lock
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/connectionmanager/types.go
  pkg/common/vclib/constants.go
  pkg/common/vclib/custom_errors.go
  pkg/common/vclib/datacenter.go
  pkg/common/vclib/datacenter_test.go
  pkg/common/vclib/datastore.go
  pkg/common/vclib/storagepod.go
  pkg/common/vclib/virtualmachine.go
  pkg/csi/service/fcd/constants.go
  pkg/csi/service/fcd/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#118 Fix cloudprovider test races
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#112 Implement CSI Node Stage/Unstage
  Gopkg.lock
  Gopkg.toml
  Makefile
  pkg/csi/service/node.go
  pkg/csi/service/node_test.go
  pkg/csi/service/service.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#116 CSI Node Publish/Unpublish
  pkg/csi/service/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#120 Add dvonthenen to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#119 More fixes for cloudprovider test races
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/common/connectionmanager/connectionmanager.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#117 Implement NodeGetInfo
  pkg/csi/service/node.go
  pkg/csi/service/node_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#121 Add empty response for ValidateVolumeCapabilities
  pkg/csi/service/fcd/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#123 Always create a Controller Service early
  pkg/csi/service/fcd/controller.go
  pkg/csi/service/service.go
  pkg/csi/types/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#124 Initial release of CSI YAML + Page83Data
  docs/deploying_cloud_provider_vsphere_with_rbac.md
  docs/deploying_csi_vsphere_with_rbac.md
  manifests/csi/csi-role-bindings.yaml
  manifests/csi/csi-roles.yaml
  manifests/csi/example-test.yaml
  manifests/csi/example-vsphere-pvc.yaml
  manifests/csi/example-vsphere-sc.yaml
  manifests/csi/vsphere-csi-controller-rbac.yaml
  manifests/csi/vsphere-csi-controller-ss.yaml
  manifests/csi/vsphere-csi-crd.yaml
  manifests/csi/vsphere-csi-ds.yaml
  manifests/csi/vsphere-csi-node-ds.yaml
  manifests/csi/vsphere-csi-node-rbac.yaml
  manifests/csi/vsphere-csi-pod.yaml
  pkg/csi/service/fcd/constants.go
  pkg/csi/service/fcd/controller.go
  pkg/csi/service/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#126 Update CSI container image with FS utilities
  cluster/images/csi/Dockerfile
  manifests/csi/vsphere-csi-controller-ss.yaml
  manifests/csi/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
