Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2018-11, with the labels that each got.

#92 fix typos overriden -> overriden
  docs/deploying_cloud_provider_vsphere_with_rbac.md
  manifests/controller-manager/vsphere.conf
Labels: approved, cncf-cla: yes, lgtm, size/XS

#93 Fix typos: doesnt -> does not
  pkg/cloudprovider/vsphere/cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#91 Refactor configuration gathering for all 3 projects
  docs/deploying_cloud_provider_vsphere_with_rbac.md
  manifests/controller-manager/vsphere.conf
  pkg/cli/cli.go
  pkg/cli/client.go
  pkg/cli/config.go
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphere/server/server_test.go
  pkg/cloudprovider/vsphere/types.go
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#95 Move pkg/vclib and pkg/config under pkg/common
  pkg/cli/cli.go
  pkg/cli/client.go
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/server/server_test.go
  pkg/cloudprovider/vsphere/types.go
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/common/config/config.go
  pkg/common/config/config_test.go
  pkg/common/config/types.go
  pkg/common/vclib/connection.go
  pkg/common/vclib/connection_test.go
  pkg/common/vclib/constants.go
  pkg/common/vclib/custom_errors.go
  pkg/common/vclib/datacenter.go
  pkg/common/vclib/datacenter_test.go
  pkg/common/vclib/datastore.go
  pkg/common/vclib/datastore_test.go
  pkg/common/vclib/diskmanagers/vdm.go
  pkg/common/vclib/diskmanagers/virtualdisk.go
  pkg/common/vclib/diskmanagers/vmdm.go
  pkg/common/vclib/fixtures/ca.key
  pkg/common/vclib/fixtures/ca.pem
  pkg/common/vclib/fixtures/createCerts.sh
  pkg/common/vclib/fixtures/fixtures.go
  pkg/common/vclib/fixtures/invalid.pem
  pkg/common/vclib/fixtures/server.csr
  pkg/common/vclib/fixtures/server.key
  pkg/common/vclib/fixtures/server.pem
  pkg/common/vclib/folder.go
  pkg/common/vclib/folder_test.go
  pkg/common/vclib/pbm.go
  pkg/common/vclib/utils.go
  pkg/common/vclib/utils_test.go
  pkg/common/vclib/virtualmachine.go
  pkg/common/vclib/virtualmachine_test.go
  pkg/common/vclib/vmoptions.go
  pkg/common/vclib/volumeoptions.go
  pkg/common/vclib/vsphere_metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#96 Restore Network configuration section and add deprecation notice
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/common/config/config.go
  pkg/common/config/types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#98 Fix typos: genrate -> generate
  pkg/cloudprovider/vsphere/cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#97 Move CredMgr to pkg/common, add DCOS/generic-CO support
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/types.go
  pkg/common/config/config.go
  pkg/common/config/types.go
  pkg/common/credentialmanager/credentialmanager.go
  pkg/common/credentialmanager/credentialmanager_test.go
  pkg/common/credentialmanager/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#100 fix logging calls
  pkg/common/vclib/connection.go
  pkg/common/vclib/datacenter.go
  pkg/common/vclib/diskmanagers/vmdm.go
  pkg/common/vclib/pbm.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#99 Fix a batch of typos
  cmd/vcpctl/main.go
  docs/vcpctl.md
  pkg/common/vclib/virtualmachine.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#101 Refactor vSphere Connection into a Connection Manager for CSI reuse
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphere/types.go
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/common/config/config.go
  pkg/common/config/types.go
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/connectionmanager/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#102 Remove dead/stale code
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/common/config/config.go
  pkg/common/config/types.go
Labels: approved, cncf-cla: yes, lgtm, size/S
