Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2019-03, with the labels that each got.

#150 Fix broken cron builds that rely on fork=true
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#151 e2e: Sonobuoy
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#154 Update embargo doc link in SECURITY_OWNERS and change PST to PSC
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#153 CSI ginkgo
  Gopkg.lock
  Gopkg.toml
  Makefile
  pkg/csi/testing/csi_suite_test.go
  pkg/csi/testing/plugin_startup_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#156 Go module support; require Go 1.11+; new Makefile
  .gitignore
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  Makefile
  README.md
  cluster/images/controller-manager/.gitignore
  cluster/images/csi/.gitignore
  go.mod
  go.sum
  hack/.golint_failures
  hack/make.sh
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#159 Make Env Vars take precedence over config file
  pkg/cli/cli.go
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/instances_test.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/cloudprovider/vsphere/zones_test.go
  pkg/common/config/config.go
  pkg/common/config/config_test.go
  pkg/common/connectionmanager/list_test.go
  pkg/common/connectionmanager/search_test.go
  pkg/common/connectionmanager/zones_test.go
  pkg/csi/service/fcd/controller_test.go
  pkg/csi/service/service.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#161 Address flaky TestGRPCServerClient in `make test`
  pkg/cloudprovider/vsphere/proto/cloudprovidervsphere.pb.go
  pkg/cloudprovider/vsphere/proto/cloudprovidervsphere.proto
  pkg/cloudprovider/vsphere/server/client.go
  pkg/cloudprovider/vsphere/server/server.go
  pkg/cloudprovider/vsphere/server/server_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#163 Fix format, vet, lint, and logic errors
  Makefile
  cmd/vcpctl/main.go
  cmd/vcpctl/provision/provision.go
  cmd/vsphere-cloud-controller-manager/main.go
  pkg/cli/cli.go
  pkg/cli/client.go
  pkg/cli/test/vcsim.go
  pkg/cli/user.go
  pkg/cli/util.go
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphere/server/client.go
  pkg/cloudprovider/vsphere/server/server.go
  pkg/cloudprovider/vsphere/server/server_test.go
  pkg/cloudprovider/vsphere/types.go
  pkg/cloudprovider/vsphere/util.go
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/cloudprovider/vsphere/zones.go
  pkg/common/config/config.go
  pkg/common/config/config_test.go
  pkg/common/config/types.go
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/connectionmanager/list.go
  pkg/common/connectionmanager/list_test.go
  pkg/common/connectionmanager/search.go
  pkg/common/connectionmanager/search_test.go
  pkg/common/connectionmanager/types.go
  pkg/common/connectionmanager/zones.go
  pkg/common/credentialmanager/credentialmanager.go
  pkg/common/credentialmanager/types.go
  pkg/common/kubernetes/types.go
  pkg/common/vclib/constants.go
  pkg/common/vclib/datacenter.go
  pkg/common/vclib/datastore.go
  pkg/common/vclib/fcd.go
  pkg/common/vclib/folder.go
  pkg/common/vclib/pbm.go
  pkg/common/vclib/utils.go
  pkg/common/vclib/virtualmachine.go
  pkg/common/vclib/volumeoptions.go
  pkg/csi/service/fcd/constants.go
  pkg/csi/service/fcd/controller.go
  pkg/csi/service/fcd/controller_test.go
  pkg/csi/service/fcd/vsphere_helper.go
  pkg/csi/service/identity.go
  pkg/csi/service/node.go
  pkg/csi/service/service.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#165 Only report IPs bound to vNICs
  pkg/cloudprovider/vsphere/nodemanager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#164 Add env var to disable CSI K8s client
  cmd/vsphere-csi/main.go
  pkg/cloudprovider/vsphere/cloud.go
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/kubernetes/informers.go
  pkg/common/kubernetes/types.go
  pkg/csi/service/fcd/controller.go
  pkg/csi/service/service.go
  pkg/csi/types/envvars.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#155 Add e2e integration tests using vcSim and Kind
  test/integration/.gitignore
  test/integration/Makefile
  test/integration/create-vms.sh
  test/integration/secrets.yaml
  test/integration/vsphere.conf
  test/kind/c01-product-serial.txt
  test/kind/c01-product-uuid.txt
  test/kind/kind-config.yaml
  test/kind/w01-product-serial.txt
  test/kind/w01-product-uuid.txt
  test/vcsim/Dockerfile
  test/vcsim/Makefile
  test/vcsim/deployment.yaml
  test/vcsim/entrypoint.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#166 Enable linting on Prow
  Makefile
  hack/check.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#168 Add descriptive instanceType to nodes
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#167 Support for running e2e against the CCM and CSI controllers from Prow
  .dockerignore
  .gitignore
  Makefile
  hack/check.sh
  hack/images/ci/Dockerfile
  hack/images/ci/Makefile
  hack/images/ci/README.md
  hack/images/ci/conformance.sh
  hack/images/golang/Dockerfile
  hack/make.sh
  hack/make/docker.mk
  hack/make/login-to-image-registry.mk
  test/integration/Makefile
  test/integration/create-vms.sh
  test/kind/kind-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#169 Updates to CI and conformance work
  Makefile
  e2e-job.yaml
  hack/images/ci/Dockerfile
  hack/images/ci/Makefile
  hack/make/ldflags.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#173 Fix linting issues
  pkg/csi/service/fcd/controller.go
  pkg/csi/types/envvars.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#174 ci: Update the version of sk8e2e to fix CI bug
  hack/images/ci/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#175 ci: Fix CI conformance with new network ID
  hack/images/ci/conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
