Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2019-07, with the labels that each got.

#208 Add InstanceShutdownByProviderID implementation
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#211 Fixed log lines not appearing when using klog.V(X) and glog.
  cmd/vsphere-cloud-controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#184 use string data for example vSphere secret manifest
  manifests/controller-manager/vccm-secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#215 Refactor WhichVCandDCByZone Lookup starting w/ Host using Ancestors()
  pkg/cloudprovider/vsphere/zones.go
  pkg/common/connectionmanager/zones.go
  pkg/common/connectionmanager/zones_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#213 Update docs for secret using stringdata
  docs/book/tutorials/deploying_cloud_provider_vsphere_with_rbac.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#217 publish ccm binaries to google storage
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#216 Fix repo owners file
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/M

#221 Update the version string used in Makefiles
  Makefile
  hack/images/ci/Makefile
  test/integration/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#223 Add/fix markdown linting
  .markdownlintrc
  CONTRIBUTING.md
  Makefile
  README.md
  docs/book/README.md
  docs/book/cloud_config.md
  docs/book/cluster_architecture.md
  docs/book/components_and_tools.md
  docs/book/installation_and_operations.md
  docs/book/kubernetes_concepts.md
  docs/book/tutorials/deploying_ccm_and_csi_with_multi_dc_vc_aka_zones.md
  docs/book/tutorials/deploying_cloud_provider_vsphere_with_rbac.md
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
  docs/book/vsphere_integrations.md
  docs/design/refactor-design.md
  docs/tools/vcpctl.md
  hack/check-mdlint.sh
  hack/images/ci/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#224 Add seperate linting scripts
  Makefile
  go.sum
  hack/check-format.sh
  hack/check-lint.sh
  hack/check-vet.sh
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/proto/cloudprovidervsphere.pb.go
  pkg/cloudprovider/vsphere/zones_test.go
  pkg/common/credentialmanager/types.go
  pkg/common/kubernetes/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#225 Remove hack/check.sh
  Makefile
  hack/check.sh
Labels: approved, cncf-cla: yes, lgtm, size/M
