Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2019-09, with the labels that each got.

#244 Refactor using single SharedInformer
  pkg/cloudprovider/vsphere/cloud.go
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/kubernetes/informers.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#236 Tutorial updates
  docs/book/README.md
  docs/book/tutorials/deploying_cloud_provider_vsphere_with_rbac.md
  docs/book/tutorials/k8s-vcp-on-vsphere-with-kubeadm.md
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
  docs/images/cns-mongo-pvs-labels.png
  docs/images/cns-mongo-pvs.png
  docs/images/space-efficient.png
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#248 Fix image URLs in kubeadm + vsphere tutorial
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#249 Further doc updates based on feedback
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#250 Adjust log levels for cloud provider interface calls
  pkg/cloudprovider/vsphere/cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#253 Controller manifest update to point to apps/v1 to replace deprecated extensions/v1beta1
  manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
