Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2019-05, with the labels that each got.

#183 Remove CSI from CI container image
  hack/images/ci/Dockerfile
  hack/images/ci/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#187 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#188 Fix typos
  docs/vcpctl.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
