Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2019-11, with the labels that each got.

#274 Always ensure KIND is present for integration test
  test/integration/Makefile
  test/integration/install_kind.sh
  test/kind/kind-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#273 Fix failing go test in connection_test.go
  pkg/common/vclib/connection_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#271 Locate InternalIP and ExternalIP by vSphere Network name
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/config.go
  pkg/cloudprovider/vsphere/config_test.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/types.go
  pkg/cloudprovider/vsphere/vsphere_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
