Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2019-12, with the labels that each got.

#283 Make informer factory a singleton
  pkg/common/kubernetes/informers.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#286 Updating docs related to vsphere-csi
  docs/book/tutorials/deploying_cpi_and_csi_with_multi_dc_vc_aka_zones.md
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#280 Doc Updates to Include Helm Instructions
  README.md
  docs/book/tutorials/kubernetes-on-vsphere-with-helm.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#282 Report Active Nodes Only
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/proto/cloudprovidervsphere.pb.go
  pkg/cloudprovider/vsphere/proto/cloudprovidervsphere.proto
  pkg/cloudprovider/vsphere/server/server.go
  pkg/cloudprovider/vsphere/server/server_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#284 Allow Internal/External status.Address Filtering by VM Network Name
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/config.go
  pkg/cloudprovider/vsphere/config_test.go
  pkg/cloudprovider/vsphere/instances_test.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphere/types.go
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/cloudprovider/vsphere/zones_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
