Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2019-02, with the labels that each got.

#136 Initial Implementation for CSI multi-VC/DC Support
  docs/deploying_ccm_and_csi_with_multi_dc_vc_aka_zones.md
  docs/deploying_csi_vsphere_with_rbac.md
  manifests/controller-manager/example-test.yaml
  manifests/controller-manager/kubeadm.conf
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
  manifests/controller-manager/vsphere.conf
  manifests/csi/example-test-pod.yaml
  manifests/csi/example-test.yaml
  manifests/csi/example-vsphere-pvc.yaml
  manifests/csi/example-vsphere-sc.yaml
  manifests/csi/vsphere-csi-controller-ss.yaml
  manifests/csi/vsphere-csi-crd.yaml
  manifests/csi/vsphere-csi-node-ds.yaml
  manifests/csi/vsphere.conf
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/zones.go
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/connectionmanager/custom_errors.go
  pkg/common/connectionmanager/list.go
  pkg/common/connectionmanager/search.go
  pkg/common/connectionmanager/types.go
  pkg/common/connectionmanager/zones.go
  pkg/common/vclib/custom_errors.go
  pkg/common/vclib/datacenter.go
  pkg/csi/service/fcd/constants.go
  pkg/csi/service/fcd/controller.go
  pkg/csi/service/fcd/vsphere_helper.go
  pkg/csi/service/identity.go
  pkg/csi/service/service.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#140 Switch from using glog to klog
  Gopkg.lock
  cmd/vsphere-cloud-controller-manager/main.go
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/server/server.go
  pkg/cloudprovider/vsphere/zones.go
  pkg/common/config/config.go
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/connectionmanager/list.go
  pkg/common/connectionmanager/search.go
  pkg/common/connectionmanager/zones.go
  pkg/common/credentialmanager/credentialmanager.go
  pkg/common/kubernetes/kubernetes.go
  pkg/common/vclib/connection.go
  pkg/common/vclib/datacenter.go
  pkg/common/vclib/datastore.go
  pkg/common/vclib/folder.go
  pkg/common/vclib/pbm.go
  pkg/common/vclib/storagepod.go
  pkg/common/vclib/utils.go
  pkg/common/vclib/virtualmachine.go
  pkg/common/vclib/volumeoptions.go
  pkg/csi/service/service.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#141 Check for min vCenter version
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/vclib/connection.go
  pkg/csi/service/fcd/controller.go
  pkg/csi/service/fcd/vsphere_helper.go
  pkg/csi/service/fcd/vsphere_helper_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#143 Bug fix for NodeManager and Photon 2 UUID
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphere/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#145 Clarification on CCM and CSI Documentation
  docs/deploying_cloud_provider_vsphere_with_rbac.md
  docs/deploying_csi_vsphere_with_rbac.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#148 Use vcsim SearchIndex in nodemanager test
  pkg/cloudprovider/vsphere/nodemanager_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#147 Part 1: Add CSI go tests
  Gopkg.lock
  pkg/cloudprovider/vsphere/zones_test.go
  pkg/common/connectionmanager/zones.go
  pkg/common/vclib/custom_errors.go
  pkg/common/vclib/datacenter.go
  pkg/common/vclib/virtualmachine.go
  pkg/csi/service/fcd/controller.go
  pkg/csi/service/fcd/controller_test.go
  pkg/csi/service/fcd/vsphere_helper_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#149 Part 2: More go tests
  Gopkg.lock
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/instances_test.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphere/util_test.go
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/cloudprovider/vsphere/zones_test.go
  pkg/common/connectionmanager/list_test.go
  pkg/common/connectionmanager/search_test.go
  pkg/common/connectionmanager/zones_test.go
  pkg/csi/service/fcd/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL
