Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2019-08, with the labels that each got.

#227 Use bash for conformance.sh script
  hack/images/ci/conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#228 Rev up k/k dependency to 1.15
  Makefile
  cmd/vsphere-cloud-controller-manager/main.go
  go.mod
  go.sum
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/instances_test.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/types.go
  pkg/cloudprovider/vsphere/zones.go
  vendor/bitbucket.org/ww/goautoneg/Makefile
  vendor/bitbucket.org/ww/goautoneg/README.txt
  vendor/bitbucket.org/ww/goautoneg/autoneg.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#229 Add token auth support for tags client
  pkg/cloudprovider/vsphere/zones_test.go
  pkg/common/connectionmanager/zones.go
  pkg/common/vclib/connection.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#230 Update README.md with link to quickstart
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#231 IPv6 Support
  go.mod
  manifests/controller-manager/cloud-controller-manager-role-bindings.yaml
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphere/util.go
  pkg/common/config/config.go
  pkg/common/config/config_test.go
  pkg/common/config/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#232 Update and clean up vSphere Cloud Provider docs
  docs/book/README.md
  docs/book/SUMMARY.md
  docs/book/cloud_provider_interface.md
  docs/book/cluster_architecture.md
  docs/book/concepts/cpi_overview.md
  docs/book/concepts/csi_overview.md
  docs/book/concepts/in_tree_vs_out_of_tree.md
  docs/book/concepts/vcp_overview.md
  docs/book/concepts/vmware_vsphere_storage.md
  docs/book/container_storage_interface.md
  docs/book/glossary.md
  docs/book/installation_and_operations.md
  docs/book/kubernetes_concepts.md
  docs/book/vsphere_integrations.md
  docs/images/cpi_node_addresses_example.png
  docs/images/cpi_nodes_instance_type_example.png
  docs/images/cpi_zones_topology_example.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#235 docs: fix link to CSI page
  docs/book/SUMMARY.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#226 Introduce new release tooling and structure
  Makefile
  cluster/images/controller-manager/Dockerfile
  hack/match-release-tag.sh
  hack/release.sh
  manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
  test/integration/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/L

#237 Fix import syntax in cloudprovidervsphere.pb.go
  pkg/cloudprovider/vsphere/proto/cloudprovidervsphere.pb.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#238 Fix tagging of latest in hack/release.sh
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#239 Add links to container images to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#240 Fix build output location in release.sh
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#241 Initial commit for handling multiple secrets
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/instances_test.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphere/proto/cloudprovidervsphere.pb.go
  pkg/cloudprovider/vsphere/types.go
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/cloudprovider/vsphere/zones.go
  pkg/cloudprovider/vsphere/zones_test.go
  pkg/common/config/config.go
  pkg/common/config/config_test.go
  pkg/common/config/consts_and_errors.go
  pkg/common/config/types.go
  pkg/common/config/virtualcenterconfig.go
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/connectionmanager/consts_and_errors.go
  pkg/common/connectionmanager/custom_errors.go
  pkg/common/connectionmanager/list.go
  pkg/common/connectionmanager/list_test.go
  pkg/common/connectionmanager/search.go
  pkg/common/connectionmanager/search_test.go
  pkg/common/connectionmanager/types.go
  pkg/common/connectionmanager/zones.go
  pkg/common/connectionmanager/zones_test.go
  pkg/common/credentialmanager/consts_and_errors.go
  pkg/common/credentialmanager/credentialmanager.go
  pkg/common/credentialmanager/credentialmanager_test.go
  pkg/common/credentialmanager/types.go
  pkg/common/kubernetes/informers.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
