Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2019-10, with the labels that each got.

#254 Updated docs to use manifest yaml links rather than copy and paste
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#256 Update README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#260 remove ServiceAccount in cloud config
  pkg/cloudprovider/vsphere/cloud.go
  pkg/common/config/config.go
  pkg/common/config/consts_and_errors.go
  pkg/common/config/types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#258 Update CI image
  cluster/images/controller-manager/Dockerfile
  hack/images/ci/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#257 Update Go docker images to 1.12.10
  cluster/images/controller-manager/Dockerfile
  hack/images/ci/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#263 Docs: Min Supported Version & Removal of In-Tree Config
  docs/book/README.md
  docs/book/SUMMARY.md
  docs/book/cloud_config.md
  docs/book/tutorials/deploying_cloud_provider_vsphere_with_rbac.md
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#264 docs: add in-tree tutorial to SUMMARY.md otherwise page is not rendered
  docs/book/SUMMARY.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#267 Modify CPI to Use k8s Secrets
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#269 [Docs] Added firewall considerations and adjusted header levels
  docs/book/concepts/csi_overview.md
  docs/book/container_storage_interface.md
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/M
