Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2019-04, with the labels that each got.

#176 Add Block Volume support
  pkg/csi/service/node.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#177 ci: Update sk8e2e image in CI image
  hack/images/ci/Dockerfile
  hack/images/ci/conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#182 Remove CSI code from repo
  .dockerignore
  .gitignore
  Makefile
  README.md
  cluster/images/csi/.gitignore
  cluster/images/csi/Dockerfile
  cmd/vsphere-csi/main.go
  docs/deploying_ccm_and_csi_with_multi_dc_vc_aka_zones.md
  docs/deploying_csi_vsphere_with_rbac.md
  go.mod
  go.sum
  manifests/csi/example-test-pod.yaml
  manifests/csi/example-vsphere-pvc.yaml
  manifests/csi/example-vsphere-sc.yaml
  manifests/csi/vcsi-secret.yaml
  manifests/csi/vsphere-csi-controller-rbac.yaml
  manifests/csi/vsphere-csi-controller-ss.yaml
  manifests/csi/vsphere-csi-crd.yaml
  manifests/csi/vsphere-csi-node-ds.yaml
  manifests/csi/vsphere-csi-node-rbac.yaml
  manifests/csi/vsphere.conf
  pkg/csi/provider/provider.go
  pkg/csi/service/fcd/constants.go
  pkg/csi/service/fcd/controller.go
  pkg/csi/service/fcd/controller_test.go
  pkg/csi/service/fcd/custom_errors.go
  pkg/csi/service/fcd/vsphere_helper.go
  pkg/csi/service/fcd/vsphere_helper_test.go
  pkg/csi/service/identity.go
  pkg/csi/service/node.go
  pkg/csi/service/node_test.go
  pkg/csi/service/service.go
  pkg/csi/testing/csi_suite_test.go
  pkg/csi/testing/plugin_startup_test.go
  pkg/csi/types/envvars.go
  pkg/csi/types/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
