Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2019-06, with the labels that each got.

#189 Fix logging for vendored packages
  cmd/vsphere-cloud-controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#190 Updating with images for docs
  docs/images/clusterbased.png
  docs/images/datacenterbased.png
  docs/images/pitfalls.png
  docs/images/whichdatastore.png
Labels: approved, cncf-cla: yes, lgtm, size/XS

#191 Fix README links
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#181 vSphere Cloud Provider Documentation
  docs/book/.gitignore
  docs/book/README.md
  docs/book/SUMMARY.md
  docs/book/cloud_config.md
  docs/book/cluster_architecture.md
  docs/book/components_and_tools.md
  docs/book/images/clusterbased.png
  docs/book/images/datacenterbased.png
  docs/book/images/in-tree-arch.png
  docs/book/images/out-of-tree-arch.png
  docs/book/images/pitfalls.png
  docs/book/images/vCenter.png
  docs/book/images/vsphere-in-tree-architecture.png
  docs/book/images/vsphere-out-of-tree-architecture.png
  docs/book/images/whichdatastore.png
  docs/book/installation_and_operations.md
  docs/book/kubernetes_concepts.md
  docs/book/tutorials/deploying_ccm_and_csi_with_multi_dc_vc_aka_zones.md
  docs/book/tutorials/deploying_cloud_provider_vsphere_with_rbac.md
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
  docs/book/vsphere_integrations.md
  docs/design/refactor-design.md
  docs/images/in-tree-arch.png
  docs/images/out-of-tree-arch.png
  docs/images/vCenter.png
  docs/images/vsphere-in-tree-architecture.png
  docs/images/vsphere-out-of-tree-architecture.png
  docs/tools/vcpctl.md
  hack/build-gitbooks.sh
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#193 redirect to cloud-provider-vsphere.sigs.k8s.io in netlify.toml
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#192 Update docs to include images and help clarify certain scenarios for zones
  docs/book/tutorials/deploying_ccm_and_csi_with_multi_dc_vc_aka_zones.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#196 docs: use full raw github content URLs for images
  docs/book/cluster_architecture.md
  docs/book/images/clusterbased.png
  docs/book/images/datacenterbased.png
  docs/book/images/in-tree-arch.png
  docs/book/images/out-of-tree-arch.png
  docs/book/images/pitfalls.png
  docs/book/images/vCenter.png
  docs/book/images/vsphere-in-tree-architecture.png
  docs/book/images/vsphere-out-of-tree-architecture.png
  docs/book/images/whichdatastore.png
  docs/book/kubernetes_concepts.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#195 add order-only pre-req for deploy, as it's beeing skipped when recursing
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#194 fix broken go get on the kind stage
  hack/images/ci/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#197 bump sk8e2e to pickup fixes on ELB timeouts
  hack/images/ci/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#198 Fix dead tutorial links
  docs/book/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#199 Add Link for Zones Support tutorial to vSphere Integration
  docs/book/vsphere_integrations.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#203 Implement Lookup VM by IP
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/util.go
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/connectionmanager/search.go
  pkg/common/vclib/datacenter.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#205 Fix UUID/ProviderID to only use lower case based on VC and k8s matching/lookup
  pkg/cloudprovider/vsphere/instances_test.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/util.go
  pkg/cloudprovider/vsphere/util_test.go
  pkg/common/connectionmanager/search.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#206 bump sk8 to pickup fixes
  hack/images/ci/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS
