Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2020-06, with the labels that each got.

#339 vSphere cloud-controller-manager should tolerate not-ready taint
  manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#347 typos
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#346 Update cloud_provider_interface.md
  docs/book/cloud_provider_interface.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#344 Update config.go
  pkg/cloudprovider/vsphere/config.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#342 Update CSI driver documentation
  docs/book/tutorials/enabling-vsphere-csi-on-an-existing-cluster.md
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
