Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2020-05, with the labels that each got.

#335 Revert "fix invalid url"
  README.md
Labels: cncf-cla: yes, size/XS

#336 Don't cache instances if addresses are not found
  pkg/cloudprovider/vsphere/instances_test.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/cloudprovider/vsphere/zones_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#337 set gitVersion in cloud-controller-manager LDFLAGS
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS
