Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2020-11, with the labels that each got.

#401 Bump k8s.io/kubernetes to 1.19.3
  go.mod
  go.sum
  pkg/cloudprovider/vsphere/cloud.go
  pkg/common/kubernetes/informers.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#370 Version-based release manifests
  manifests/controller-manager/README.md
  manifests/controller-manager/cloud-controller-manager-roles.yaml
  releases/latest/vsphere-cloud-controller-manager.yaml
  releases/v1.2/vsphere-cloud-controller-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#402 lock image tags to v1.2.1 for deprecated example manifests
  manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
  releases/latest/vsphere-cloud-controller-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#403 remove latest tagging during releases
  Makefile
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#382 Align YAML with the Helm Chart PR
  releases/v1.18/vsphere-cloud-controller-manager.yaml
  test/integration/Makefile
  test/integration/secrets.yaml
  test/integration/vsphere.conf
Labels: approved, cncf-cla: yes, lgtm, size/L

#408 allow create/update for leases.coordination.k8s.io
  manifests/controller-manager/cloud-controller-manager-roles.yaml
  releases/v1.2/vsphere-cloud-controller-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#411 Fixes integration tests
  test/integration/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#412 Upgrade kind version for integration tests
  test/integration/Makefile
  test/integration/install_kind.sh
  test/vcsim/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#394 support remote authentication for NSX-T load balancer
  go.mod
  go.sum
  pkg/cloudprovider/vsphere/loadbalancer/access.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config_ini_legacy.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config_ini_legacy_test.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config_yaml.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config_yaml_test.go
  pkg/cloudprovider/vsphere/loadbalancer/config/types_common.go
  pkg/cloudprovider/vsphere/loadbalancer/config/types_ini_legacy.go
  pkg/cloudprovider/vsphere/loadbalancer/config/types_yaml.go
  pkg/cloudprovider/vsphere/loadbalancer/lbprovider.go
  pkg/cloudprovider/vsphere/loadbalancer/nsxt_broker.go
  pkg/cloudprovider/vsphere/loadbalancer/state.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#392 Use Exists operator in node-role.kubernetes.io/master toleration
  releases/v1.18/vsphere-cloud-controller-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
