Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2020-07, with the labels that each got.

#343 return err if VM guest property is nil
  pkg/cloudprovider/vsphere/nodemanager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#350 skip staticcheck for SA1019
  hack/check-staticcheck.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#352 Remove ToLower when using FQDN
  pkg/common/credentialmanager/credentialmanager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#349 Update docs for VMTools exclude-nics filtering
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#305 Initial implementation for YAML based config
  docs/book/tutorials/deploying_cpi_and_csi_with_multi_dc_vc_aka_zones.md
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
  go.mod
  go.sum
  manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
  pkg/cli/cli.go
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/config/config.go
  pkg/cloudprovider/vsphere/config/config_ini_legacy.go
  pkg/cloudprovider/vsphere/config/config_ini_legacy_test.go
  pkg/cloudprovider/vsphere/config/config_yaml.go
  pkg/cloudprovider/vsphere/config/config_yaml_test.go
  pkg/cloudprovider/vsphere/config/types_common.go
  pkg/cloudprovider/vsphere/config/types_ini_legacy.go
  pkg/cloudprovider/vsphere/config/types_yaml.go
  pkg/cloudprovider/vsphere/loadbalancer/README.md
  pkg/cloudprovider/vsphere/loadbalancer/class.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config_ini_legacy.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config_ini_legacy_test.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config_yaml.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config_yaml_test.go
  pkg/cloudprovider/vsphere/loadbalancer/config/consts_and_errors.go
  pkg/cloudprovider/vsphere/loadbalancer/config/types_common.go
  pkg/cloudprovider/vsphere/loadbalancer/config/types_ini_legacy.go
  pkg/cloudprovider/vsphere/loadbalancer/config/types_yaml.go
  pkg/cloudprovider/vsphere/loadbalancer/lbprovider.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/types.go
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/common/config/config.go
  pkg/common/config/config_ini_legacy.go
  pkg/common/config/config_ini_legacy_test.go
  pkg/common/config/config_yaml.go
  pkg/common/config/config_yaml_test.go
  pkg/common/config/consts_and_errors.go
  pkg/common/config/types_common.go
  pkg/common/config/types_ini_legacy.go
  pkg/common/config/types_yaml.go
  pkg/common/config/virtualcenterconfig.go
  pkg/common/connectionmanager/list_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#355 Fixed a bug in InstanceExistsByProviderID()
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#358 Documentation How-To for CPI version 1.1.0 and earlier
  docs/book/tutorials/deploying_cpi_and_csi_with_multi_dc_vc_aka_zones.md
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#361 Log does not print node initialization success when zone labels are not configured
  pkg/cloudprovider/vsphere/zones.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#359 InstanceExistsByProviderID Signal Deletion to K8s
  docs/book/tutorials/deploying_cpi_and_csi_with_multi_dc_vc_aka_zones.md
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#362 Add support for Resource Pool and Folder traversal for Zones/Regions
  pkg/cloudprovider/vsphere/zones.go
  pkg/common/connectionmanager/zones.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#365 instances: return InstanceNotFound error in InstanceID
  pkg/cloudprovider/vsphere/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#366 Update kubernetes-on-vsphere-with-helm.md
  docs/book/tutorials/kubernetes-on-vsphere-with-helm.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#367 Update README.md
  pkg/cloudprovider/vsphere/loadbalancer/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
