Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2020-08, with the labels that each got.

#360 Add repo SECURITY.md
  SECURITY.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#369 fix version logging on start up
  cmd/vsphere-cloud-controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#372 docs: add a Known Issues section
  docs/book/README.md
  docs/book/SUMMARY.md
  docs/book/known_issues.md
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#376 Remove inactive members from OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#363 Bump k8s.io/kubernetes to v1.18.6
  cluster/images/controller-manager/Dockerfile
  cmd/vsphere-cloud-controller-manager/main.go
  go.mod
  go.sum
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/loadbalancer/cleanup.go
  pkg/cloudprovider/vsphere/zones.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#377 README for vcsim keys used in go test
  pkg/common/vclib/fixtures/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#379 Update kubernetes-on-vsphere-with-helm.md
  docs/book/tutorials/kubernetes-on-vsphere-with-helm.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#383 nodemanager: wait for hostname before registering node
  pkg/cloudprovider/vsphere/instances_test.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/common/connectionmanager/search.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#385 Cherry-pick PR 383 to v1.2
  pkg/cloudprovider/vsphere/instances_test.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/common/connectionmanager/search.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#378 External/Internal Address Discovery Fix
  pkg/cloudprovider/vsphere/nodemanager.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#386 Cherry Pick 378: External/Internal Address Discovery Fix
  pkg/cloudprovider/vsphere/nodemanager.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#388 Cherrypick 387 to release-1.2
  pkg/cloudprovider/vsphere/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#387 Skip node deletion by VM name due to race conditions with vmtools
  pkg/cloudprovider/vsphere/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S
