Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2020-03, with the labels that each got.

#301 Minor edits in container_storage_interface.md
  docs/book/container_storage_interface.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#292 Support for NSX-T based Load Balancers
  cmd/vsphere-cloud-controller-manager/main.go
  go.mod
  go.sum
  hack/release.sh
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/config.go
  pkg/cloudprovider/vsphere/loadbalancer/README.md
  pkg/cloudprovider/vsphere/loadbalancer/access.go
  pkg/cloudprovider/vsphere/loadbalancer/class.go
  pkg/cloudprovider/vsphere/loadbalancer/cleanup.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config_test.go
  pkg/cloudprovider/vsphere/loadbalancer/helpers.go
  pkg/cloudprovider/vsphere/loadbalancer/interface.go
  pkg/cloudprovider/vsphere/loadbalancer/lbprovider.go
  pkg/cloudprovider/vsphere/loadbalancer/lbservice.go
  pkg/cloudprovider/vsphere/loadbalancer/lock.go
  pkg/cloudprovider/vsphere/loadbalancer/mapping.go
  pkg/cloudprovider/vsphere/loadbalancer/nsxt_broker.go
  pkg/cloudprovider/vsphere/loadbalancer/nsxt_type_converter.go
  pkg/cloudprovider/vsphere/loadbalancer/state.go
  pkg/cloudprovider/vsphere/loadbalancer/tag.go
  pkg/cloudprovider/vsphere/loadbalancer/tag_test.go
  pkg/cloudprovider/vsphere/types.go
  pkg/cloudprovider/vsphere/vapilogger.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#303 fix/typo: removed typo in line 5
  docs/book/concepts/csi_overview.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#293 Added guide on how to install CSI on an already-existing K8s cluster
  .markdownlintrc
  docs/book/tutorials/enabling-vsphere-csi-on-an-existing-cluster.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#309 Update README.md
  docs/book/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
