Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2020-12, with the labels that each got.

#405 Move nsxt connection part to a separate dir
  go.mod
  go.sum
  pkg/cloudprovider/vsphere/loadbalancer/config/config.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config_ini_legacy.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config_yaml.go
  pkg/cloudprovider/vsphere/loadbalancer/config/types_common.go
  pkg/cloudprovider/vsphere/loadbalancer/config/types_ini_legacy.go
  pkg/cloudprovider/vsphere/loadbalancer/config/types_yaml.go
  pkg/cloudprovider/vsphere/loadbalancer/nsxt_broker.go
  pkg/nsxt/config/config.go
  pkg/nsxt/config/config_ini_legacy.go
  pkg/nsxt/config/config_ini_legacy_test.go
  pkg/nsxt/config/config_test.go
  pkg/nsxt/config/config_yaml.go
  pkg/nsxt/config/config_yaml_test.go
  pkg/nsxt/config/types_common.go
  pkg/nsxt/config/types_ini_legacy.go
  pkg/nsxt/config/types_yaml.go
  pkg/nsxt/nsxt_connector.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#414 Revert k8s.io/kubernetes to 1.18.12
  go.mod
  go.sum
  pkg/cloudprovider/vsphere/cloud.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#417 Update deploying_cpi_and_csi_with_multi_dc_vc_aka_zones.md
  docs/book/tutorials/deploying_cpi_and_csi_with_multi_dc_vc_aka_zones.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#418 Update kubernetes-on-vsphere-with-helm.md
  docs/book/tutorials/kubernetes-on-vsphere-with-helm.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
