Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2020-04, with the labels that each got.

#313 Fix OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#311 Update glossary.md
  docs/book/glossary.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#315 Update vmware_vsphere_storage.md
  docs/book/concepts/vmware_vsphere_storage.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#314 Typo fix for vcpctl provision long description
  cmd/vcpctl/provision/provision.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#317 Add services/status patch role for service type:LoadBalancer controllers
  manifests/controller-manager/cloud-controller-manager-roles.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#318 Patch 1
  docs/book/concepts/in_tree_vs_out_of_tree.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#319 Patch 2
  docs/book/concepts/vcp_overview.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#320 Update SUMMARY.md
  docs/book/SUMMARY.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#310 Added detail to CPI/CSI how-to doc to clarify ProviderID requirement
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#322 Patch 1
  docs/book/concepts/cpi_overview.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#323 Add files via upload
  docs/images/vsphere-in-tree-architecture.png
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#325 Editing csi_overview.md
  docs/book/concepts/csi_overview.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#321 support NSX-T connection with proxy
  pkg/cloudprovider/vsphere/loadbalancer/nsxt_broker.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#328 fix invalid url
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#329 fix invalid url
  README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#330 fix invalid url
  docs/book/cloud_provider_interface.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS
