Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2021-12, with the labels that each got.

#532 Add notifier for config map updates.
  cmd/vsphere-cloud-controller-manager/main.go
  go.mod
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#535 show vsphere-cloud-controller-manager version in the log correctly
  Makefile
  cluster/images/controller-manager/Dockerfile
Labels: size/XS, cncf-cla: yes, approved, lgtm, ok-to-test

#540 Remove cached node based on UUID when unregister node
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#542 Add Han Fang as reviewer
  OWNERS_ALIASES
Labels: size/XS, cncf-cla: yes, approved

#541 Do not use the cached node addresses when NodeAddresses is invoked.
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/instances_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#539 Add release guide doc
  docs/book/README.md
  docs/book/tutorials/make_a_new_cpi_release.md
Labels: cncf-cla: yes, size/M, approved, lgtm

#543 Cherry pick node cache fix 1.22
  Makefile
  cluster/images/controller-manager/Dockerfile
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/instances_test.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#546 For paravirtual, empty ProviderUUID appears for node
  pkg/cloudprovider/vsphereparavirtual/instances.go
  pkg/cloudprovider/vsphereparavirtual/instances_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#547 1.22 Cherry pick fix for reporting error empty uuid when finding instance, this is for paravirtual
  pkg/cloudprovider/vsphereparavirtual/instances.go
  pkg/cloudprovider/vsphereparavirtual/instances_test.go
Labels: cncf-cla: yes, approved, size/S

#548 Update doc and tag to point to 1.22.4
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/deploying-cpi-with-k3s.md
  docs/book/tutorials/disable-node-deletion.yaml
  index.yaml
  releases/README.md
  releases/v1.22/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, approved, size/S, ok-to-test

#544 chart: allow configuration of configmap and secret name
  charts/vsphere-cpi/README.md
  charts/vsphere-cpi/templates/configmap.yaml
  charts/vsphere-cpi/templates/daemonset.yaml
  charts/vsphere-cpi/templates/secret.yaml
  charts/vsphere-cpi/values.yaml
Labels: cncf-cla: yes, needs-ok-to-test, approved, size/S, lgtm

#550 Remove dead code
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#553 Adds implementation for returning zones for nodes.
  go.mod
  go.sum
  pkg/cloudprovider/vsphereparavirtual/cloud.go
  pkg/cloudprovider/vsphereparavirtual/instances.go
  pkg/cloudprovider/vsphereparavirtual/types.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator.go
  pkg/cloudprovider/vsphereparavirtual/zone.go
  pkg/cloudprovider/vsphereparavirtual/zone_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#555 cherrypick crossport zone support for 1.22
  go.mod
  go.sum
  pkg/cloudprovider/vsphereparavirtual/cloud.go
  pkg/cloudprovider/vsphereparavirtual/instances.go
  pkg/cloudprovider/vsphereparavirtual/types.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator.go
  pkg/cloudprovider/vsphereparavirtual/zone.go
  pkg/cloudprovider/vsphereparavirtual/zone_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#551 Initiate E2E tests for vsphere-cpi
  .gitignore
  Makefile
  go.mod
  go.sum
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  pkg/cloudprovider/vsphereparavirtual/instances_test.go
  pkg/cloudprovider/vsphereparavirtual/loadbalancer_test.go
  pkg/cloudprovider/vsphereparavirtual/vmservice/vmservice_test.go
  pkg/util/fake_client_wrapper.go
  test/e2e/Makefile
  test/e2e/README.md
  test/e2e/config/vsphere-dev.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/sanity_test.go
  test/e2e/vsphere.go
Labels: cncf-cla: yes, needs-ok-to-test, approved, size/XXL, lgtm

#557 Adds implementation for returning zones for nodes.
  pkg/cloudprovider/vsphereparavirtual/apis/nsxnetworking/v1alpha1/zz_generated.deepcopy.go
  pkg/cloudprovider/vsphereparavirtual/cloud.go
  pkg/cloudprovider/vsphereparavirtual/instances.go
  pkg/cloudprovider/vsphereparavirtual/types.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator.go
  pkg/cloudprovider/vsphereparavirtual/zone.go
  pkg/cloudprovider/vsphereparavirtual/zone_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test
