Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2021-06, with the labels that each got.

#467 Update RouteSet CRD
  pkg/cloudprovider/vsphereparavirtual/apis/nsxnetworking/v1alpha1/routeset_types.go
  pkg/cloudprovider/vsphereparavirtual/apis/nsxnetworking/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#471 Add lubronzhan to the maintainer list
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#472 Add nicolehanjing to maintainer list
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#460 docs: Improve documents/tutorials and fix broken links
  README.md
  docs/book/SUMMARY.md
  docs/book/cloud_provider_interface.md
  docs/images/vsphere_kubernetes_logo.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#468 Implement Route interface and add the script to generate client code
  Makefile
  go.mod
  go.sum
  hack/boilerplate.go.txt
  hack/tools.go
  hack/update-codegen.sh
  hack/verify-codegen.sh
  pkg/cloudprovider/vsphere/route/routeprovider.go
  pkg/cloudprovider/vsphere/route/routeprovider_test.go
  pkg/cloudprovider/vsphereparavirtual/cloud.go
  pkg/cloudprovider/vsphereparavirtual/instances_test.go
  pkg/cloudprovider/vsphereparavirtual/loadbalancer_test.go
  pkg/cloudprovider/vsphereparavirtual/route.go
  pkg/cloudprovider/vsphereparavirtual/route_test.go
  pkg/cloudprovider/vsphereparavirtual/types.go
  pkg/cloudprovider/vsphereparavirtual/vmservice/vmservice_test.go
  pkg/util/fake_client_wrapper.go
  pkg/util/fake_routeset_client_wrapper.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#469 Add node and ippool controllers to do node ipam
  cmd/vsphere-cloud-controller-manager/main.go
  go.mod
  go.sum
  pkg/cloudprovider/vsphereparavirtual/cloud.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/core.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/helper/ippool.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ippool/ippool_controller.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ippool/ippool_controller_test.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/node/node_controller.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/node/node_controller_test.go
  pkg/common/kubernetes/informers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#477 Use Ippool's status as source of truth. Regardless cidr value, assign…
  pkg/cloudprovider/vsphereparavirtual/cloud.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ippool/ippool_controller.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ippool/ippool_controller_test.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/node/node_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#459 Add docs for providing release version matrix
  CONTRIBUTING.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#473 Add script to squash all commits of current branch and build docker image
  Makefile
  hack/git-squash.sh
Labels: approved, cncf-cla: yes, lgtm, size/M
