Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2021-03, with the labels that each got.

#439 Revert dual stack nodes because GuestNicInfo does not guarentee network name
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#440 [v1.18] Revert dual stack nodes because GuestNicInfo does not guarentee network name
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#441 [v1,19] Revert dual stack nodes because GuestNicInfo does not guarentee network name
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#434 Fix cloud provider flag error - "--cloud-provider cannot be empty"
  cmd/vsphere-cloud-controller-manager/main.go
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/L

#443 Enable vsphere paravirtual cloud provider
  cmd/vsphere-cloud-controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#445 Add maplain to the maintainer list
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#448 Change the providerID Prefix of vsphere-paravirtual to 'vsphere'
  cmd/vsphere-cloud-controller-manager/main.go
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/util.go
  pkg/cloudprovider/vsphereparavirtual/cloud.go
  pkg/cloudprovider/vsphereparavirtual/instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#452 Remove Travis CI check
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/L
