Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2021-07, with the labels that each got.

#481 Fix link in in_tree_vs_out_of_tree.md
  docs/book/concepts/in_tree_vs_out_of_tree.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#486 fix issue 485: panic error after not finding matching VM in k3s
  pkg/cloudprovider/vsphere/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#478 Migrate the helm chart to /charts repo and update related docs
  charts/vsphere-cpi/.helmignore
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/README.md
  charts/vsphere-cpi/templates/NOTES.txt
  charts/vsphere-cpi/templates/_helpers.tpl
  charts/vsphere-cpi/templates/common.yaml
  charts/vsphere-cpi/templates/configmap.yaml
  charts/vsphere-cpi/templates/daemonset.yaml
  charts/vsphere-cpi/templates/ingress.yaml
  charts/vsphere-cpi/templates/podsecuritypolicy.yaml
  charts/vsphere-cpi/templates/role-binding.yaml
  charts/vsphere-cpi/templates/role.yaml
  charts/vsphere-cpi/templates/secret.yaml
  charts/vsphere-cpi/templates/service-account.yaml
  charts/vsphere-cpi/templates/service.yaml
  charts/vsphere-cpi/values.yaml
  docs/book/tutorials/kubernetes-on-vsphere-with-helm.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#487 add v1.20 and v1.21 manifests
  releases/v1.20/vsphere-cloud-controller-manager.yaml
  releases/v1.21/vsphere-cloud-controller-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#488 doc: deploy cpi with k3s
  docs/book/tutorials/deploying-cpi-with-k3s.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#491 update helm related docs
  charts/vsphere-cpi/README.md
  charts/vsphere-cpi/templates/NOTES.txt
  charts/vsphere-cpi/values.yaml
  docs/book/tutorials/kubernetes-on-vsphere-with-helm.md
  index.yaml
Labels: approved, cncf-cla: yes, size/M

#492 fix helm docs and update helm charts
  charts/vsphere-cpi-1.0.0.tgz
  charts/vsphere-cpi/README.md
  index.yaml
Labels: approved, cncf-cla: yes, size/S

#493 fix helm commands
  charts/vsphere-cpi/README.md
  docs/book/tutorials/kubernetes-on-vsphere-with-helm.md
  index.yaml
  vsphere-cpi-1.0.0.tgz
Labels: approved, cncf-cla: yes, size/S

#494 Update out of date helm charts and related docs
  .github/workflows/release.yml
  charts/vsphere-cpi-1.0.0.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/README.md
  charts/vsphere-cpi/templates/NOTES.txt
  charts/vsphere-cpi/templates/common.yaml
  charts/vsphere-cpi/templates/configmap.yaml
  charts/vsphere-cpi/templates/daemonset.yaml
  charts/vsphere-cpi/templates/ingress.yaml
  charts/vsphere-cpi/templates/role-binding.yaml
  charts/vsphere-cpi/templates/role.yaml
  charts/vsphere-cpi/templates/secret.yaml
  charts/vsphere-cpi/templates/service-account.yaml
  charts/vsphere-cpi/values.yaml
  docs/book/tutorials/kubernetes-on-vsphere-with-helm.md
  index.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#495 helm chart template fix: fix configMap name in volumes settings
  charts/vsphere-cpi-1.0.0.tgz
  charts/vsphere-cpi/templates/daemonset.yaml
  index.yaml
Labels: approved, cncf-cla: yes, size/XS
