Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2021-01, with the labels that each got.

#407 Add route interfaces
  go.mod
  go.sum
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/route/config/config.go
  pkg/cloudprovider/vsphere/route/config/config_ini_legacy.go
  pkg/cloudprovider/vsphere/route/config/config_ini_legacy_test.go
  pkg/cloudprovider/vsphere/route/config/config_yaml.go
  pkg/cloudprovider/vsphere/route/config/config_yaml_test.go
  pkg/cloudprovider/vsphere/route/config/consts_and_errors.go
  pkg/cloudprovider/vsphere/route/config/types_common.go
  pkg/cloudprovider/vsphere/route/config/types_ini_legacy.go
  pkg/cloudprovider/vsphere/route/config/types_yaml.go
  pkg/cloudprovider/vsphere/route/mock_nsxtbroker.go
  pkg/cloudprovider/vsphere/route/nsxtbroker.go
  pkg/cloudprovider/vsphere/route/routeprovider.go
  pkg/cloudprovider/vsphere/route/routeprovider_test.go
  pkg/cloudprovider/vsphere/types.go
  pkg/cloudprovider/vsphere/vsphere_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#416 Change CPI to use klog/v2 (Structured logging)
  cmd/vsphere-cloud-controller-manager/main.go
  go.mod
  pkg/cli/cli.go
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/config/config.go
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/loadbalancer/cleanup.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config_ini_legacy.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config_yaml.go
  pkg/cloudprovider/vsphere/loadbalancer/state.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/server/client.go
  pkg/cloudprovider/vsphere/server/server.go
  pkg/cloudprovider/vsphere/util.go
  pkg/cloudprovider/vsphere/vapilogger.go
  pkg/cloudprovider/vsphere/zones.go
  pkg/common/config/config.go
  pkg/common/config/config_ini_legacy.go
  pkg/common/config/config_yaml.go
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/connectionmanager/list.go
  pkg/common/connectionmanager/search.go
  pkg/common/connectionmanager/zones.go
  pkg/common/credentialmanager/credentialmanager.go
  pkg/common/kubernetes/kubernetes.go
  pkg/common/vclib/connection.go
  pkg/common/vclib/datacenter.go
  pkg/common/vclib/datastore.go
  pkg/common/vclib/folder.go
  pkg/common/vclib/pbm.go
  pkg/common/vclib/storagepod.go
  pkg/common/vclib/utils.go
  pkg/common/vclib/virtualmachine.go
  pkg/common/vclib/volumeoptions.go
  pkg/nsxt/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#420 Refactor routes implementation for better testability
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/route/config/config_ini_legacy.go
  pkg/cloudprovider/vsphere/route/config/config_yaml.go
  pkg/cloudprovider/vsphere/route/nsxtbroker.go
  pkg/cloudprovider/vsphere/route/routeprovider.go
  pkg/cloudprovider/vsphere/route/routeprovider_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#422 Validate certificate in NSXT config
  go.sum
  pkg/cloudprovider/vsphere/route/config/config.go
  pkg/cloudprovider/vsphere/route/routeprovider.go
  pkg/nsxt/config/config_ini_legacy.go
  pkg/nsxt/config/config_ini_legacy_test.go
  pkg/nsxt/config/config_yaml.go
  pkg/nsxt/config/config_yaml_test.go
  pkg/nsxt/nsxt_connector.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#425 Remove NSX-T LB alpha feature gate
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/cloud_test.go
  pkg/cloudprovider/vsphere/route/config/config.go
  pkg/cloudprovider/vsphere/vsphere_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#426 Fix nil pointer error if the connector manager config is not set
  pkg/nsxt/connector_manager.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#424 Bump k8s.io/kubernetes to 1.19.7 and add back InstancesV2
  cluster/images/controller-manager/Dockerfile
  go.mod
  go.sum
  hack/images/ci/Dockerfile
  pkg/cloudprovider/vsphere/cloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#415 Add in 1.19 YAML into master
  releases/v1.19/vsphere-cloud-controller-manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#429 Bump k8s.io/kubernetes to 1.20.2
  cmd/vsphere-cloud-controller-manager/main.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#430 Clean up go.mod to remove k8s.io/kubernetes
  go.mod
  go.sum
  pkg/common/credentialmanager/credentialmanager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL
