Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2021-11, with the labels that each got.

#520 Add doc on disabling node deletion when VM is not found
  docs/book/tutorials/disable-node-deletion.md
  docs/book/tutorials/disable-node-deletion.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#522 disable node registration when UUID is empty
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/nodemanager.go
Labels: size/XS, cncf-cla: yes, approved, lgtm

#524 Internal & External subnets accepts multiple CIDRs
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#528 chart: fix helm errors by quoting credentials
  charts/vsphere-cpi/templates/secret.yaml
Labels: size/XS, cncf-cla: yes, needs-ok-to-test, approved, lgtm

#530 Remove CSI docs and update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/failing-test.yaml
  .github/ISSUE_TEMPLATE/flaking-test.yaml
  README.md
  docs/book/README.md
  docs/book/SUMMARY.md
  docs/book/cloud_provider_interface.md
  docs/book/concepts/cpi_overview.md
  docs/book/concepts/csi_overview.md
  docs/book/container_storage_interface.md
  docs/book/tutorials/deploying_cpi_with_multi_dc_vc_aka_zones.md
  docs/book/tutorials/enabling-vsphere-csi-on-an-existing-cluster.md
  releases/README.md
  releases/v1.22/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, size/XL, approved, lgtm
