Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2022-12, with the labels that each got.

#670 Fix cve 1.23
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#669 Fix cve 1.24
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#671 Fix cve and update go to 1.17 - release 1.22
  cluster/images/controller-manager/Dockerfile
  go.mod
  go.sum
  hack/images/ci/Dockerfile
Labels: cncf-cla: yes, approved, size/L, lgtm

#668 Fix node affinity format
  releases/v1.25/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm

#666 Load vSphere Credentials by SecretsDirectory
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/credentialmanager/credentialmanager.go
  pkg/common/credentialmanager/credentialmanager_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#675 Cherrypick 1.24 credential manager change
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/credentialmanager/consts_and_errors.go
  pkg/common/credentialmanager/credentialmanager.go
  pkg/common/credentialmanager/credentialmanager_test.go
  releases/README.md
Labels: cncf-cla: yes, approved, size/L, lgtm
