Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2022-01, with the labels that each got.

#556 Exclude subnets for node ip selection
  pkg/cloudprovider/vsphere/config/config_ini_legacy.go
  pkg/cloudprovider/vsphere/config/config_ini_legacy_test.go
  pkg/cloudprovider/vsphere/config/config_yaml.go
  pkg/cloudprovider/vsphere/config/config_yaml_test.go
  pkg/cloudprovider/vsphere/config/types_common.go
  pkg/cloudprovider/vsphere/config/types_ini_legacy.go
  pkg/cloudprovider/vsphere/config/types_yaml.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#559 add documentation for cloud config Nodes values
  docs/book/cloud_config.md
  pkg/cloudprovider/vsphere/nodemanager.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#558 Bump cloud-provider-vsphere to k8s v1.23
  cluster/images/controller-manager/Dockerfile
  go.mod
  go.sum
  hack/images/ci/Dockerfile
Labels: cncf-cla: yes, approved, size/L, lgtm

#562 Fix staticcheck error by cluster-api dependency.
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm, ¯\_(ツ)_/¯, ok-to-test

#563 Remove extra key name in chart release config
  .github/workflows/release.yml
Labels: size/XS, cncf-cla: yes, approved, lgtm

#560 Return an error if multiple VMs with the same hostname was found
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/common/vclib/custom_errors.go
  pkg/common/vclib/datacenter.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#564 Update helm chart release
  charts/vsphere-cpi-1.0.0.tgz
  charts/vsphere-cpi/templates/daemonset.yaml
  index.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm

#567 Backport node ip exclusion to 1.22 branch
  docs/book/cloud_config.md
  pkg/cloudprovider/vsphere/config/config_ini_legacy.go
  pkg/cloudprovider/vsphere/config/config_ini_legacy_test.go
  pkg/cloudprovider/vsphere/config/config_yaml.go
  pkg/cloudprovider/vsphere/config/config_yaml_test.go
  pkg/cloudprovider/vsphere/config/types_common.go
  pkg/cloudprovider/vsphere/config/types_ini_legacy.go
  pkg/cloudprovider/vsphere/config/types_yaml.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test

#566 Wrong vCenter IP in kubernetes-on-vsphere-with-kubeadm.md secrets example
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: size/XS, cncf-cla: yes, needs-ok-to-test, approved, lgtm

#568 Bump to 1.22.5
  .github/workflows/release.yml
  charts/vsphere-cpi-1.0.0.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/templates/daemonset.yaml
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/deploying-cpi-with-k3s.md
  docs/book/tutorials/disable-node-deletion.yaml
  index.yaml
  releases/README.md
  releases/v1.22/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#569 Patch priorityClassName: system-node-critical in CPI daemonset
  charts/vsphere-cpi/templates/daemonset.yaml
  releases/v1.18/vsphere-cloud-controller-manager.yaml
  releases/v1.19/vsphere-cloud-controller-manager.yaml
  releases/v1.2/vsphere-cloud-controller-manager.yaml
  releases/v1.20/vsphere-cloud-controller-manager.yaml
  releases/v1.21/vsphere-cloud-controller-manager.yaml
  releases/v1.22/vsphere-cloud-controller-manager.yaml
Labels: size/XS, cncf-cla: yes, approved, lgtm, ok-to-test

#571 [Cherry Pick] Patch priorityClassName: system-node-critical in CPI daemonset
  charts/vsphere-cpi/templates/daemonset.yaml
  releases/v1.18/vsphere-cloud-controller-manager.yaml
  releases/v1.19/vsphere-cloud-controller-manager.yaml
  releases/v1.2/vsphere-cloud-controller-manager.yaml
  releases/v1.20/vsphere-cloud-controller-manager.yaml
  releases/v1.21/vsphere-cloud-controller-manager.yaml
  releases/v1.22/vsphere-cloud-controller-manager.yaml
Labels: size/XS, cncf-cla: yes, needs-ok-to-test, approved, lgtm

#572 Deprecate pod priority annotation in cpi deployment
  charts/vsphere-cpi/templates/daemonset.yaml
  docs/book/tutorials/disable-node-deletion.yaml
  releases/v1.18/vsphere-cloud-controller-manager.yaml
  releases/v1.19/vsphere-cloud-controller-manager.yaml
  releases/v1.20/vsphere-cloud-controller-manager.yaml
  releases/v1.21/vsphere-cloud-controller-manager.yaml
  releases/v1.22/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, needs-ok-to-test, approved, size/S, lgtm

#570 Add script for test coverage pipeline
  .gitignore
  Makefile
  scripts/ci-test-coverage.sh
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#573 [Cherry-Pick] Deprecate pod priority annotation in cpi deployment
  charts/vsphere-cpi/templates/daemonset.yaml
  docs/book/tutorials/disable-node-deletion.yaml
  releases/v1.18/vsphere-cloud-controller-manager.yaml
  releases/v1.19/vsphere-cloud-controller-manager.yaml
  releases/v1.20/vsphere-cloud-controller-manager.yaml
  releases/v1.21/vsphere-cloud-controller-manager.yaml
  releases/v1.22/vsphere-cloud-controller-manager.yaml
  releases/v1.23/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, needs-ok-to-test, approved, size/S, lgtm

#575 Skip e2e for calculating coverage
  test/e2e/e2e_suite_test.go
Labels: size/XS, cncf-cla: yes, approved

#577 Refactor unit-test and test-cover in MAKEFILE
  Makefile
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#579 [Cherry-Pick] Add test coverage for 1.22
  .gitignore
  Makefile
  scripts/ci-test-coverage.sh
Labels: cncf-cla: yes, needs-ok-to-test, size/M, approved, lgtm

#578 [Cherry-Pick] Add test coverage for 1.21
  .gitignore
  Makefile
  scripts/ci-test-coverage.sh
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#581 [cherry pick]Fix staticcheck error by cluster-api dependency.
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm
