Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2022-06, with the labels that each got.

#626 Bump cloud-provider-vsphere to k8s v1.24
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XL, approved, lgtm, ok-to-test

#627 Remove grpc server from the cloud-controller-manager.
  charts/vsphere-cpi/templates/daemonset.yaml
  go.mod
  go.sum
  hack/release.sh
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphere/proto/cloudprovidervsphere.pb.go
  pkg/cloudprovider/vsphere/proto/cloudprovidervsphere.proto
  pkg/cloudprovider/vsphere/server/client.go
  pkg/cloudprovider/vsphere/server/server.go
  pkg/cloudprovider/vsphere/server/server_test.go
  pkg/cloudprovider/vsphere/types.go
  pkg/common/config/config.go
  pkg/common/config/config_ini_legacy.go
  pkg/common/config/config_yaml.go
  pkg/common/config/types_common.go
Labels: cncf-cla: yes, approved, size/XXL, lgtm, ok-to-test

#630 Bump version to 1.23.1.
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/deploying-cpi-with-k3s.md
  docs/book/tutorials/disable-node-deletion.yaml
  index.yaml
  releases/README.md
  releases/v1.23/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm

#632 Change config to Publish chart on each release branch
  .github/workflows/release.yml
Labels: size/XS, cncf-cla: yes, approved

#636 Document the least required vCenter permissions for CPV
  docs/book/vcp_roles.md
Labels: cncf-cla: yes, approved, size/S, lgtm
