Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2022-02, with the labels that each got.

#580 [Cherry-Pick] Add test coverage for 1.23
  .gitignore
  Makefile
  scripts/ci-test-coverage.sh
  test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#585 Return error when VM's info returned from VC doesn't contains IP address
  pkg/cloudprovider/vsphere/nodemanager.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#586 [Cherrypick 1.22] Return error when VM's info returned from VC doesn't contains IP address
  pkg/cloudprovider/vsphere/nodemanager.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#587 [Cherrypick 1.23] Return error when VM's info returned from VC doesn't contains IP address
  pkg/cloudprovider/vsphere/nodemanager.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#594 Fixed broken link
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: size/XS, cncf-cla: yes, approved, lgtm, ok-to-test

#596 Add xudong liu as cloud provider vsphere maintainer
  OWNERS_ALIASES
Labels: size/XS, cncf-cla: yes, approved, lgtm

#590 [1.21] Add missing logic to pass RemoteAuth when constructing Config
  pkg/nsxt/config/config_ini_legacy.go
  pkg/nsxt/config/config_ini_legacy_test.go
  pkg/nsxt/config/config_yaml.go
  pkg/nsxt/config/config_yaml_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#591 [1.22] Add missing logic to pass RemoteAuth when constructing Config
  pkg/nsxt/config/config_ini_legacy.go
  pkg/nsxt/config/config_ini_legacy_test.go
  pkg/nsxt/config/config_yaml.go
  pkg/nsxt/config/config_yaml_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#592 [1.23] Fix logic to correctly read and pass along value `nsxt.RemoteAuth` in config.
  pkg/nsxt/config/config_ini_legacy.go
  pkg/nsxt/config/config_ini_legacy_test.go
  pkg/nsxt/config/config_yaml.go
  pkg/nsxt/config/config_yaml_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm
