Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2022-08, with the labels that each got.

#589 Add missing logic to pass RemoteAuth when constructing Config
  pkg/nsxt/config/config_ini_legacy.go
  pkg/nsxt/config/config_ini_legacy_test.go
  pkg/nsxt/config/config_yaml.go
  pkg/nsxt/config/config_yaml_test.go
Labels: lifecycle/rotten, cncf-cla: yes, size/M, approved, ok-to-test

#645 Fix helm_doc
  charts/vsphere-cpi/README.md
Labels: size/XS, cncf-cla: yes, approved, lgtm

#643 Use full resource path for ipclaim and ipaddress in e2e CI.
  hack/e2e.sh
  hack/release.sh
  test/e2e/config/vsphere-ci.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#646 Release 1.24.1
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/disable-node-deletion.yaml
  go.mod
  go.sum
  index.yaml
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/util.go
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/cloudprovider/vsphereparavirtual/client/clientset/versioned/fake/register.go
  pkg/cloudprovider/vsphereparavirtual/client/clientset/versioned/scheme/register.go
  pkg/cloudprovider/vsphereparavirtual/cloud.go
  pkg/cloudprovider/vsphereparavirtual/vmservice/vmservice.go
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/connectionmanager/zones.go
  pkg/common/vclib/utils.go
  pkg/nsxt/config/config_ini_legacy.go
  pkg/nsxt/config/config_ini_legacy_test.go
  pkg/nsxt/config/config_yaml.go
  pkg/nsxt/config/config_yaml_test.go
  releases/v1.24/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, approved, size/L

#647 Update helm chart, remove the service, add rke type nodeselector
  charts/vsphere-cpi-1.24.0.tgz
  charts/vsphere-cpi-1.24.1.tgz
  charts/vsphere-cpi/README.md
  charts/vsphere-cpi/templates/NOTES.txt
  charts/vsphere-cpi/templates/daemonset.yaml
  charts/vsphere-cpi/templates/ingress.yaml
  charts/vsphere-cpi/templates/service.yaml
  charts/vsphere-cpi/values.yaml
  index.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#644 Formatted code
  go.mod
  go.sum
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/util.go
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/cloudprovider/vsphereparavirtual/client/clientset/versioned/fake/register.go
  pkg/cloudprovider/vsphereparavirtual/client/clientset/versioned/scheme/register.go
  pkg/cloudprovider/vsphereparavirtual/cloud.go
  pkg/cloudprovider/vsphereparavirtual/vmservice/vmservice.go
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/connectionmanager/zones.go
  pkg/common/vclib/utils.go
Labels: cncf-cla: yes, size/M, ok-to-test

#639 Clean up and refactor the logic for CCM entrypoint.
  cmd/vsphere-cloud-controller-manager/main.go
  hack/release.sh
Labels: cncf-cla: yes, approved, size/L, lgtm

#649 Don't trigger helm chart release to each release branch. Since not en…
  .github/workflows/release.yml
Labels: size/XS, cncf-cla: yes, approved, lgtm

#641 CredentialsManager accepts alternate Secret format
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
  pkg/common/credentialmanager/consts_and_errors.go
  pkg/common/credentialmanager/credentialmanager.go
  pkg/common/credentialmanager/credentialmanager_test.go
  releases/README.md
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test
