Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2022-04, with the labels that each got.

#612 Fix the error wrapping
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ippool/ippool_controller_test.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/node/node_controller_test.go
  pkg/common/vclib/pbm.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#613 [1.23] Cherrypick govc bump
  go.mod
  go.sum
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ippool/ippool_controller_test.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/node/node_controller_test.go
  pkg/common/vclib/connection_test.go
  pkg/common/vclib/pbm.go
  pkg/common/vclib/storagepod_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#616 Fix E2E issue where cert-manager fails to install
  go.mod
  go.sum
  test/e2e/config/vsphere-dev.yaml
  test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#617 Bump cpi version to 1.23.0
  charts/vsphere-cpi-1.0.0.tgz
  charts/vsphere-cpi-1.23.0.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/deploying-cpi-with-k3s.md
  docs/book/tutorials/disable-node-deletion.yaml
  index.yaml
  releases/README.md
  releases/v1.23/vsphere-cloud-controller-manager.yaml
  test/e2e/config/vsphere-dev.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#582 Update cluster and node selector labels for paravirutal mode
  pkg/cloudprovider/vsphereparavirtual/vmservice/vmservice.go
Labels: size/XS, cncf-cla: yes, approved, lgtm

#618 [Cherrypick 1.23] Update cluster and node selector labels for paravirutal mode
  pkg/cloudprovider/vsphereparavirtual/vmservice/vmservice.go
Labels: size/XS, cncf-cla: yes, approved

#615 Hook up CPI E2E tests with test-infra.
  Makefile
  hack/e2e.sh
  hack/ensure-kubectl.sh
  test/e2e/Makefile
  test/e2e/config/vsphere-dev.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/vsphere.go
Labels: cncf-cla: yes, approved, size/L

#619 Use TMC infra to run E2E CI jobs.
  Makefile
  cmd/vsphere-cloud-controller-manager/main.go
  hack/e2e.sh
  hack/images/ci/Dockerfile
  hack/ipclaim-template.yaml
  test/e2e/Makefile
  test/e2e/config/vsphere-dev.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, approved, size/XXL, lgtm
