Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2022-03, with the labels that each got.

#602 [Cherrypick 1.21] Backport CPI fix on empty provider uuid
  pkg/cloudprovider/vsphereparavirtual/instances.go
  pkg/cloudprovider/vsphereparavirtual/instances_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#604 Cut CPI release 1.21.2
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/values.yaml
  docs/book/tutorials/deploying-cpi-with-k3s.md
  index.yaml
  releases/v1.21/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm

#607 Back port fixes to 1.21
  .github/workflows/release.yml
  Makefile
  charts/vsphere-cpi-1.0.0.tgz
  charts/vsphere-cpi-1.21.3.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/deploying-cpi-with-k3s.md
  go.sum
  hack/check-format.sh
  hack/check-lint.sh
  hack/check-staticcheck.sh
  index.yaml
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/instances_test.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ippool/ippool_controller_test.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/node/node_controller_test.go
  releases/v1.21/vsphere-cloud-controller-manager.yaml
  test/vcsim/Dockerfile
Labels: cncf-cla: yes, approved, size/L, lgtm

#610 Back port fixes to 1.20
  hack/check-format.sh
  hack/check-lint.sh
  hack/check-staticcheck.sh
  pkg/cloudprovider/vsphere/instances.go
  pkg/cloudprovider/vsphere/instances_test.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphereparavirtual/instances.go
  pkg/cloudprovider/vsphereparavirtual/instances_test.go
  releases/v1.20/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, size/L, lgtm

#611 Add test for empty ip 1.22
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ippool/ippool_controller_test.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/node/node_controller_test.go
Labels: cncf-cla: yes, approved, size/S

#605 Bump govmomi to 0.27.3
  go.mod
  go.sum
  pkg/common/vclib/connection_test.go
  pkg/common/vclib/storagepod_test.go
Labels: cncf-cla: yes, approved, size/S
