Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2023-01, with the labels that each got.

#678 Update the KEP link for cloud-controller-manager
  README.md
Labels: size/XS, cncf-cla: yes, approved, lgtm

#682 e2e test when VM is deleted from VC, node should be recreated
  test/e2e/cpi_vm_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#683 Cherrypick PR 668 to release 1.25
  releases/v1.25/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test
