Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2023-02, with the labels that each got.

#681 Delete node if VM's MOR not found
  pkg/common/vclib/virtualmachine.go
  test/e2e/cpi_vm_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#687 Update registry k8s.gcr.io -> registry.k8s.io
  docs/book/tutorials/k8s-vcp-on-vsphere-with-kubeadm.md
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: cncf-cla: yes, size/M, approved, lgtm

#686 Update Dockerfile
  cluster/images/controller-manager/Dockerfile
Labels: size/XS, cncf-cla: yes, approved, lgtm, ok-to-test

#691 [1.24] cherrypick node not getting deleted fix and e2e test
  pkg/common/vclib/virtualmachine.go
  test/e2e/cpi_vm_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#692 [CVE 1.24] Bump gopkg.in/yaml.v3
  go.mod
  go.sum
Labels: size/XS, cncf-cla: yes, approved, lgtm

#690 [1.25] cherrypick node not getting deleted and e2e, bump golang govmomi
  go.mod
  go.sum
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/common/connectionmanager/list_test.go
  pkg/common/vclib/virtualmachine.go
  test/e2e/cpi_vm_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#693 [CVE 1.22] Bump gopkg.in/yaml.v3
  go.mod
  go.sum
Labels: size/XS, cncf-cla: yes, approved, lgtm

#694 [CVE 1.23] Bump gopkg.in/yaml.v3
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XL, approved, lgtm
