Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2023-03, with the labels that each got.

#689 update kubernetes dependency to 1.26.1
  go.mod
  go.sum
  pkg/util/fake_client_wrapper.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#697 Release 1.25.1
  charts/vsphere-cpi-1.25.1.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/README.md
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/deploying-cpi-with-k3s.md
  docs/book/tutorials/disable-node-deletion.yaml
  index.yaml
  releases/v1.25/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#698 Release 1.24.4
  charts/vsphere-cpi-1.24.4.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/README.md
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/deploying-cpi-with-k3s.md
  docs/book/tutorials/disable-node-deletion.yaml
  index.yaml
  releases/README.md
  releases/v1.24/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#699 Release 1.23.4
  charts/vsphere-cpi-1.23.4.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/deploying-cpi-with-k3s.md
  docs/book/tutorials/disable-node-deletion.yaml
  index.yaml
  releases/README.md
  releases/v1.23/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#700 Release 1.22.8
  charts/vsphere-cpi-1.22.8.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/deploying-cpi-with-k3s.md
  docs/book/tutorials/disable-node-deletion.yaml
  index.yaml
  releases/README.md
  releases/v1.22/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#701 Fix some docs after releasing 1.26.0
  README.md
  releases/README.md
Labels: size/XS, cncf-cla: yes, approved, lgtm

#703 Remove credentials from configmap
  charts/vsphere-cpi/templates/configmap.yaml
Labels: size/XS, cncf-cla: yes, needs-ok-to-test, approved, lgtm

#705 [1.23]Fix CVE-2022-41723 by bumping golang.org/x/net to 0.8.0
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#706 [1.24]Fix CVE-2022-41723 by bumping golang.org/x/net to 0.8.0
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm
