Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2023-07, with the labels that each got.

#733 chore: remove refs to deprecated io/ioutil
  pkg/cli/cli.go
  pkg/cli/util.go
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphereparavirtual/cloud.go
  pkg/cloudprovider/vsphereparavirtual/config.go
  pkg/cloudprovider/vsphereparavirtual/config_test.go
  pkg/common/credentialmanager/credentialmanager.go
  pkg/common/vclib/connection_test.go
  pkg/nsxt/connector_manager.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#740 Simplify vcsim endpoint setup
  pkg/cloudprovider/vsphere/vsphere_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#738 Bump govmomi to 0.30.6
  go.mod
  go.sum
  pkg/common/connectionmanager/list_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#739 Bump dependency in e2e test
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#734 Improve helm chart to support global values
  charts/vsphere-cpi/templates/configmap.yaml
  charts/vsphere-cpi/templates/daemonset.yaml
  charts/vsphere-cpi/templates/secret.yaml
  charts/vsphere-cpi/values.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#743 Add helm 1.27.0
  charts/vsphere-cpi-1.27.0.tgz
  index.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm
