Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2023-08, with the labels that each got.

#744 changes_to_fix_broken_links_on_refactor_design_document
  docs/design/refactor-design.md
Labels: size/XS, cncf-cla: yes, approved, lgtm, ok-to-test

#748 Update Dockerfile
  cluster/images/controller-manager/Dockerfile
Labels: size/XS, cncf-cla: yes, approved, lgtm, ok-to-test

#749 Fix the symbol for image tag
  cluster/images/controller-manager/Dockerfile
Labels: size/XS, cncf-cla: yes, approved, lgtm

#751 Bump kubernetes 1.28
  cluster/images/controller-manager/Dockerfile
  cmd/vsphere-cloud-controller-manager/main.go
  go.mod
  go.sum
  pkg/cloudprovider/vsphereparavirtual/instances_test.go
  pkg/cloudprovider/vsphereparavirtual/loadbalancer_test.go
  pkg/cloudprovider/vsphereparavirtual/vmservice/vmservice_test.go
  pkg/cloudprovider/vsphereparavirtual/zone_test.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#754 [1.22] Fix CVE-2022-41723 by bumping golang.org/x/net to 0.8.0
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#756 Release 1.23.5
  charts/vsphere-cpi-1.23.5.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/deploying-cpi-with-k3s.md
  docs/book/tutorials/disable-node-deletion.yaml
  index.yaml
  releases/README.md
  releases/v1.23/vsphere-cloud-controller-manager.yaml
  test/e2e/config/vsphere-ci.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#758 Release 1.22.9
  charts/vsphere-cpi-1.22.9.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/deploying-cpi-with-k3s.md
  docs/book/tutorials/disable-node-deletion.yaml
  index.yaml
  releases/README.md
  releases/v1.22/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#757 Update comment inside dockerfile
  cluster/images/controller-manager/Dockerfile
Labels: size/XS, cncf-cla: yes, approved, lgtm
