Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2023-05, with the labels that each got.

#721 Use a meaningful user agent name
  pkg/common/vclib/connection.go
Labels: size/XS, cncf-cla: yes, approved, lgtm

#724 Fix error verification to work on Go 1.19 and 1.20
  pkg/common/vclib/connection_test.go
Labels: size/XS, cncf-cla: yes, approved, lgtm, ok-to-test

#725 prefer addresses that are statically configured in VM metadata
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#726 Fix tls thumbprint parameter in the helm chart
  charts/vsphere-cpi/templates/configmap.yaml
  charts/vsphere-cpi/values.yaml
Labels: size/XS, cncf-cla: yes, approved, lgtm, ok-to-test

#719 Upgrade controller dependencies
  go.mod
  go.sum
  pkg/cloudprovider/vsphere/loadbalancer/nsxt_broker.go
  pkg/cloudprovider/vsphere/loadbalancer/nsxt_type_converter.go
Labels: cncf-cla: yes, size/XL, approved, lgtm, ok-to-test

#729 Release 1.25.3
  charts/vsphere-cpi-1.25.3.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/README.md
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/deploying-cpi-with-k3s.md
  docs/book/tutorials/disable-node-deletion.yaml
  index.yaml
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/common/vclib/connection.go
  releases/v1.25/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#730 Release 1.24.6
  charts/vsphere-cpi-1.24.6.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/README.md
  charts/vsphere-cpi/values.yaml
  docs/book/tutorials/disable-node-deletion.yaml
  index.yaml
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphere/nodemanager_test.go
  pkg/common/vclib/connection.go
  releases/v1.24/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm
