Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2024-08, with the labels that each got.

#1181 ⚙️ remove useless github action configuration
  .github/workflows/promote-image.yml
  cloudbuild-pr.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#1184 ⚙️ update dependabot configuration
  .github/dependabot.yml
Labels: cncf-cla: yes, approved, size/L, lgtm

#1185 ⚙️ Fix golang static check
  pkg/cloudprovider/vsphere/loadbalancer/config/config_ini_legacy.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config_yaml.go
  pkg/cloudprovider/vsphere/loadbalancer/nsxt_broker.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ippool/ippool_controller_test.go
  pkg/cloudprovider/vsphereparavirtual/loadbalancer_test.go
  pkg/cloudprovider/vsphereparavirtual/route_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#1205 ✨ e2e test: update e2e test config to run on latest k8s
  test/e2e/Makefile
  test/e2e/config/vsphere-ci.yaml
  test/e2e/e2e_suite_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#1206 ⚙️ [release-1.31] e2e test: Cherry pick e2e test change
  test/e2e/Makefile
  test/e2e/config/vsphere-ci.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, approved, size/L

#1208 ⚙️ [release-1.29] fix golang static check
  pkg/cloudprovider/vsphere/loadbalancer/config/config_ini_legacy.go
  pkg/cloudprovider/vsphere/loadbalancer/config/config_yaml.go
  pkg/cloudprovider/vsphere/loadbalancer/nsxt_broker.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ippool/ippool_controller_test.go
  pkg/cloudprovider/vsphereparavirtual/loadbalancer_test.go
  pkg/cloudprovider/vsphereparavirtual/route_test.go
Labels: cncf-cla: yes, size/M, approved

#1209 ⚙️ fix genreate release tag github action
  .github/workflows/generate-release-notes.yml
Labels: size/XS, cncf-cla: yes, approved

#1211 ⚙️ fix auto sync gh pages github action
  .github/workflows/auto-sync-gh-pages.yml
Labels: size/XS, cncf-cla: yes, approved

#1152 Replace IPPool with IPAddressAllocation API to Claim Pod CIDR in the VPC network
  go.mod
  go.sum
  pkg/cloudprovider/vsphereparavirtual/config.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/core.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ipaddressallocation/ipaddressallocation_controller.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ipaddressallocation/ipaddressallocation_controller_test.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ippool/ippool_controller.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/node/node_controller.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/node/node_controller_test.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/utils/utils.go
  pkg/cloudprovider/vsphereparavirtual/ippoolmanager/interfaces.go
  pkg/cloudprovider/vsphereparavirtual/ippoolmanager/v1alpha1/ippoolmanager.go
  pkg/cloudprovider/vsphereparavirtual/ippoolmanager/v1alpha1/ippoolmanager_test.go
  pkg/cloudprovider/vsphereparavirtual/ippoolmanager/v1alpha2/ippoolmanager.go
  pkg/cloudprovider/vsphereparavirtual/ippoolmanager/v1alpha2/ippoolmanager_test.go
  pkg/cloudprovider/vsphereparavirtual/nsxipmanager/const.go
  pkg/cloudprovider/vsphereparavirtual/nsxipmanager/interfaces.go
  pkg/cloudprovider/vsphereparavirtual/nsxipmanager/nsx_t1.go
  pkg/cloudprovider/vsphereparavirtual/nsxipmanager/nsx_vpc.go
  pkg/cloudprovider/vsphereparavirtual/nsxipmanager/nsx_vpc_test.go
  pkg/cloudprovider/vsphereparavirtual/routemanager/staticroute/routemanager.go
  pkg/cloudprovider/vsphereparavirtual/routemanager/staticroute/routemanager_test.go
  pkg/common/kubernetes/informers.go
  pkg/util/tests.go
Labels: cncf-cla: yes, approved, size/XXL, lgtm

#1218 ⚙️ update dockerfile golang version to fix post-merge job failure
  cluster/images/controller-manager/Dockerfile
Labels: size/XS, cncf-cla: yes, approved

#1221 Bump nsx-operator mod
  go.mod
  go.sum
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ipaddressallocation/ipaddressallocation_controller.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ipaddressallocation/ipaddressallocation_controller_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#1226 [release-1.31] ✨ cherry pick nsx op api bump to release 1.31
  go.mod
  go.sum
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ipaddressallocation/ipaddressallocation_controller.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ipaddressallocation/ipaddressallocation_controller_test.go
Labels: cncf-cla: yes, approved, size/S
