Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2024-06, with the labels that each got.

#1061 fix integration test
  test/integration/Makefile
  test/integration/install_kind.sh
Labels: cncf-cla: yes, approved, size/S

#1050 test/e2e: Bump k8s 0.30.1
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#1060 update all the image registry related document
  Makefile
  README.md
  charts/vsphere-cpi-v1.30.1.tgz
  charts/vsphere-cpi/README.md
  charts/vsphere-cpi/values.yaml
  docs/book/tutorials/disable-node-deletion.yaml
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
  docs/book/tutorials/make_a_new_cpi_release.md
  hack/images/ci/README.md
  hack/make.sh
  index.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
  releases/README.md
  releases/v1.28/vsphere-cloud-controller-manager.yaml
  releases/v1.29/vsphere-cloud-controller-manager.yaml
  releases/v1.30/vsphere-cloud-controller-manager.yaml
  test/e2e/Makefile
  test/e2e/e2e_suite_test.go
  test/integration/Makefile
Labels: cncf-cla: yes, approved, size/L, lgtm

#1062 fix helm chart release
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/README.md
Labels: size/XS, cncf-cla: yes, approved

#1058 verify generate release note github action
  .github/workflows/generate-release-notes.yml
Labels: cncf-cla: yes, size/M, approved, lgtm

#1059 add github action to auto sync doc changes to gh-pages
  .github/workflows/auto-sync-gh-pages.yml
Labels: cncf-cla: yes, size/M, approved

#1066 ⚙️ Add a script to auto change all the docs, helm chart and readme
  .github/workflows/generate-release-notes.yml
  README.md
  hack/install-gh.sh
  hack/update-docs.sh
  test/integration/Makefile
Labels: cncf-cla: yes, approved, size/L

#1072 cherry pick image registry changes to release 1.29 branch
  .github/dependabot.yml
  .github/workflows/auto-release-helm-chart.yml
  .github/workflows/auto-sync-gh-pages.yml
  .github/workflows/generate-release-notes.yml
  .github/workflows/promote-image.yml
  Makefile
  README.md
  cloudbuild-nightly.yaml
  cloudbuild.yaml
  hack/e2e.sh
  hack/images/ci/Makefile
  hack/images/ci/README.md
  hack/install-gh.sh
  hack/install-helm.sh
  hack/kpromo.sh
  hack/make.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/update-docs.sh
  releases/v1.28/vsphere-cloud-controller-manager.yaml
  releases/v1.29/vsphere-cloud-controller-manager.yaml
  test/e2e/Makefile
  test/e2e/config/vsphere-ci.yaml
  test/e2e/cpi_install_test.go
  test/e2e/cpi_vm_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/Makefile
Labels: cncf-cla: yes, approved, size/XXL, lgtm

#1067 test/e2e: use vSphere projects from Boskos
  hack/e2e.sh
  test/e2e/config/vsphere-ci.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#1086 cherry pick image registry changes to release 1.28 branch
  .github/dependabot.yml
  .github/workflows/auto-release-helm-chart.yml
  .github/workflows/auto-sync-gh-pages.yml
  .github/workflows/generate-release-notes.yml
  .github/workflows/promote-image.yml
  Makefile
  README.md
  cloudbuild-nightly.yaml
  cloudbuild.yaml
  hack/e2e.sh
  hack/images/ci/Makefile
  hack/images/ci/README.md
  hack/install-gh.sh
  hack/install-helm.sh
  hack/kpromo.sh
  hack/make.sh
  hack/release.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/update-docs.sh
  releases/v1.28/vsphere-cloud-controller-manager.yaml
  test/e2e/Makefile
  test/e2e/config/vsphere-ci.yaml
  test/e2e/cpi_install_test.go
  test/e2e/cpi_vm_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/Makefile
Labels: cncf-cla: yes, approved, size/XXL, lgtm

#1089 Cherry pick e2e env change and #786 fix to release 1.28
  cmd/vsphere-cloud-controller-manager/main.go
  hack/e2e.sh
  test/e2e/config/vsphere-ci.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#1088 test/e2e: Cherry pick use vSphere projects from Boskos to release 1.29
  hack/e2e.sh
  hack/release.sh
  test/e2e/config/vsphere-ci.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#1087 test/e2e: Cherry pick use vSphere projects from Boskos to release 1.30
  hack/e2e.sh
  hack/release.sh
  test/e2e/config/vsphere-ci.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#1090 :book:[docs]: pre v1.28.1 release document update
  README.md
  charts/vsphere-cpi-v1.28.1.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/disable-node-deletion.yaml
  hack/update-docs.sh
  index.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
  releases/README.md
  releases/v1.28/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, approved, size/L

#1091 fix kpromo action
  hack/kpromo.sh
Labels: size/XS, cncf-cla: yes, approved

#1094 fix update docs script
  hack/update-docs.sh
Labels: size/XS, cncf-cla: yes, approved

#1092 :book:[docs]: pre v1.29.1 release document update
  README.md
  charts/vsphere-cpi-v1.29.1.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/disable-node-deletion.yaml
  hack/kpromo.sh
  hack/update-docs.sh
  index.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
  releases/README.md
  releases/v1.29/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, approved, size/L

#1097 fix release 1.29 github action
  .github/workflows/auto-sync-gh-pages.yml
  .github/workflows/bump-k8s-dep.yml
  .github/workflows/bump-test-k8s-dep.yml
  .github/workflows/generate-release-notes.yml
Labels: cncf-cla: yes, approved, size/L

#1099 fix release github action
  .github/workflows/auto-release-helm-chart.yml
  .github/workflows/auto-sync-gh-pages.yml
  .github/workflows/generate-release-notes.yml
Labels: cncf-cla: yes, size/M, approved

#1102 [release-1.30] cherry pick release action fix
  .github/workflows/auto-release-helm-chart.yml
  .github/workflows/auto-sync-gh-pages.yml
  .github/workflows/generate-release-notes.yml
  .github/workflows/release.yml
  hack/kpromo.sh
  hack/update-docs.sh
Labels: cncf-cla: yes, size/M, approved

#1103 [release-1.29] cherry pick release action fix
  .github/workflows/auto-release-helm-chart.yml
  .github/workflows/auto-sync-gh-pages.yml
  .github/workflows/generate-release-notes.yml
  .github/workflows/release.yml
  hack/bump-k8s-dep.sh
Labels: cncf-cla: yes, approved, size/L

#1104 [release-1.28] cherry pick release action fix
  .github/workflows/auto-release-helm-chart.yml
  .github/workflows/auto-sync-gh-pages.yml
  .github/workflows/bump-k8s-dep.yml
  .github/workflows/bump-test-k8s-dep.yml
  .github/workflows/generate-release-notes.yml
  .github/workflows/release.yml
  hack/bump-k8s-dep.sh
  hack/kpromo.sh
Labels: cncf-cla: yes, approved, size/L

#1105 [release-1.27 ]cherry pick release image registry migration, e2e env change
  Makefile
  cloudbuild-nightly.yaml
  cloudbuild.yaml
  hack/e2e.sh
  hack/images/ci/Makefile
  hack/install-helm.sh
  hack/kpromo.sh
  hack/release.sh
  test/e2e/Makefile
  test/e2e/config/vsphere-ci.yaml
  test/e2e/cpi_install_test.go
  test/e2e/cpi_vm_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/Makefile
Labels: cncf-cla: yes, approved, size/XXL, lgtm

#1117 fix generate release note action
  .github/workflows/generate-release-notes.yml
Labels: cncf-cla: yes, approved, size/S

#1123 [1.26]cherry pick release action fix
  Makefile
  cloudbuild-nightly.yaml
  cloudbuild.yaml
  hack/e2e.sh
  hack/images/ci/Makefile
  hack/install-helm.sh
  hack/kpromo.sh
  hack/release.sh
  hack/tools/go.mod
  hack/update-docs.sh
  test/e2e/Makefile
  test/e2e/config/vsphere-ci.yaml
  test/e2e/cpi_install_test.go
  test/e2e/cpi_vm_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/Makefile
Labels: cncf-cla: yes, approved, size/XXL, lgtm

#1127 ⚙️ CI: remove VSPHERE_TLS_THUMBPRINT default value and switch to sha256
  pkg/common/vclib/connection_test.go
  test/e2e/README.md
  test/e2e/config/vsphere-ci.yaml
Labels: size/XS, cncf-cla: yes, approved, lgtm
