Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2024-07, with the labels that each got.

#1126 ✨ vm-operator: migrate to vm-operator v1alpha2 api
  cluster/images/controller-manager/Dockerfile
  go.mod
  go.sum
  hack/images/ci/Dockerfile
  pkg/cloudprovider/vsphereparavirtual/instances.go
  pkg/cloudprovider/vsphereparavirtual/instances_test.go
  pkg/cloudprovider/vsphereparavirtual/loadbalancer.go
  pkg/cloudprovider/vsphereparavirtual/loadbalancer_test.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator/client/client.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator/client/fake_client.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator/client/virtualmachine_client.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator/client/virtualmachine_client_test.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator/client/virtualmachineservice_client.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator/client/virtualmachineservice_client_test.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator/interface.go
  pkg/cloudprovider/vsphereparavirtual/vmservice/types.go
  pkg/cloudprovider/vsphereparavirtual/vmservice/vmservice.go
  pkg/cloudprovider/vsphereparavirtual/vmservice/vmservice_test.go
  pkg/cloudprovider/vsphereparavirtual/zone.go
  pkg/cloudprovider/vsphereparavirtual/zone_test.go
Labels: cncf-cla: yes, size/XL, approved, lgtm

#1136 [release-1.28] 🌱 Bump github.com/vmware/govmomi from 0.30.6 to 0.37.0
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/S, lgtm

#1135 [release-1.29] 🌱 Bump github.com/vmware/govmomi from 0.30.6 to 0.37.0
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/S, lgtm

#1137 [release-1.27] 🌱 Bump github.com/vmware/govmomi from 0.30.6 to 0.37.0
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/S, lgtm

#1138 [release-1.26] 🌱 Bump github.com/vmware/govmomi from 0.30.4 to 0.37.0
  go.mod
  go.sum
  pkg/cloudprovider/vsphere/vsphere_test.go
  pkg/common/connectionmanager/list_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#1139 Fix the unknown revision error
  go.mod
  test/e2e/go.mod
Labels: size/XS, cncf-cla: yes, approved, lgtm

#1140 ⚙️ fix: downgrade vm op api to fix ci
  cluster/images/controller-manager/Dockerfile
  go.mod
  go.sum
  hack/images/ci/Dockerfile
Labels: cncf-cla: yes, approved, size/S, lgtm

#1144 ✨ Update daemonset.yaml to remove deprecated master selector
  charts/vsphere-cpi/templates/daemonset.yaml
Labels: size/XS, cncf-cla: yes, approved, lgtm

#1143 ⚙️ change ci tooling related image to cloud provider vsphere own registry
  hack/check-mdlint.sh
  hack/check-shell.sh
Labels: size/XS, cncf-cla: yes, approved, lgtm

#1150 🌱(deps) Bump the Kubernetes group to v0.31.0-beta.0
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#1148 Move DaemonSet affinities and tolerations to values.yaml to make them user manageable.
  charts/vsphere-cpi/templates/daemonset.yaml
  charts/vsphere-cpi/values.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test
