Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2024-05, with the labels that each got.

#1005 [release-1.30] Add additional members to maintainers alias
  OWNERS_ALIASES
Labels: size/XS, cncf-cla: yes, approved, lgtm

#1004 add skriss to maintainers alias
  OWNERS_ALIASES
Labels: size/XS, cncf-cla: yes, approved, lgtm, ok-to-test

#1007 [release-1.30] Add skriss owner release 1.30
  OWNERS_ALIASES
Labels: size/XS, cncf-cla: yes, approved, lgtm

#1009 [release-1.28] Add additional owners release 1.28
  OWNERS_ALIASES
Labels: size/XS, cncf-cla: yes, approved, lgtm

#1010 [release-1.27] Add additional owners release 1.27
  OWNERS_ALIASES
Labels: size/XS, cncf-cla: yes, approved, lgtm

#1006 [release-1.27]: Bump Kubernetes group dependencies to v0.27.13
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#997 Fix node name didn't get deleted from node map when node deleted
  pkg/cloudprovider/vsphere/nodemanager.go
Labels: size/XS, cncf-cla: yes, approved, lgtm

#999 Add gcp cloud build configuration for vsphere cloud provider
  .gcloudignore
  Makefile
  cloudbuild.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#1016 Add nightly cloud build yaml
  cloudbuild-nightly.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm

#1017 Add pull request cloudbuild configuration for cloud provider vsphere
  cloudbuild-pr.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm

#1018 change vsphere cpi image path
  Makefile
  cloudbuild-nightly.yaml
Labels: cncf-cla: yes, size/M, approved

#1024 Add kpromo script
  hack/kpromo.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#1025 Add kpromo action
  .github/workflows/promote-image.yml
Labels: cncf-cla: yes, size/M, approved, lgtm

#1026 fix kpromo action
  .github/workflows/promote-image.yml
  hack/kpromo.sh
Labels: cncf-cla: yes, approved, size/S, lgtm

#1028 fix virtual machine service can't be created issue
  pkg/cloudprovider/vsphereparavirtual/vmservice/vmservice.go
Labels: size/XS, cncf-cla: yes, approved, lgtm

#1029 fix virtual machine service can't be created issue
  pkg/cloudprovider/vsphereparavirtual/vmservice/vmservice.go
Labels: size/XS, cncf-cla: yes, approved

#1046 test: remove helm go dependency in e2e test
  hack/install-helm.sh
  test/e2e/Makefile
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#1045 test: use a daemonset and kubectl exec to provide images for ci test
  hack/e2e.sh
  test/e2e/Makefile
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#1051 Add hack/tools module to dependabot config
  .github/dependabot.yml
Labels: cncf-cla: yes, approved, size/S, lgtm

#1056 automatic generate release notes
  .github/workflows/auto-release-helm-chart.yml
  .github/workflows/bump-k8s-dep.yml
  .github/workflows/bump-test-k8s-dep.yml
  .github/workflows/generate-release-notes.yml
Labels: cncf-cla: yes, size/M, approved

#1049 clean up scripts to push image for vmware registry
  Makefile
  hack/ensure-kubectl.sh
  hack/images/ci/Makefile
  hack/images/ci/README.md
  hack/make/login-to-image-registry.mk
  hack/release.sh
Labels: cncf-cla: yes, approved, size/L, lgtm
