Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2024-09, with the labels that each got.

#737 Scope secret informers per namespace
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/types.go
  pkg/cloudprovider/vsphereparavirtual/cloud.go
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/kubernetes/informers.go
  pkg/common/kubernetes/types.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#1232 🌱 (chore) update golang version to 1.22 for hack/tools
  hack/tools/go.mod
  hack/tools/go.sum
Labels: cncf-cla: yes, approved, size/S, lgtm

#1250 :gear: replace pre merge check image registry
  hack/check-mdlint.sh
  hack/check-shell.sh
Labels: size/XS, cncf-cla: yes, approved, lgtm
