Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2024-04, with the labels that each got.

#981 update e2e test versions
  test/e2e/config/vsphere-ci.yaml
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#984 fix release script
  hack/release.sh
Labels: size/XS, cncf-cla: yes, approved, lgtm

#985 update dependent bot
  .github/dependabot.yml
Labels: cncf-cla: yes, size/M, approved, lgtm

#943 Add additional members to maintainers alias
  OWNERS_ALIASES
Labels: size/XS, cncf-cla: yes, approved, lgtm, ok-to-test
