Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2024-02, with the labels that each got.

#847 Remove controller runtime dependency
  go.mod
  go.sum
  pkg/cloudprovider/vsphereparavirtual/instances.go
  pkg/cloudprovider/vsphereparavirtual/instances_test.go
  pkg/cloudprovider/vsphereparavirtual/loadbalancer_test.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator/client/client.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator/client/fake_client.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator/client/virtualmachine_client.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator/client/virtualmachine_client_test.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator/client/virtualmachineservice_client.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator/client/virtualmachineservice_client_test.go
  pkg/cloudprovider/vsphereparavirtual/vmoperator/interface.go
  pkg/cloudprovider/vsphereparavirtual/vmservice/types.go
  pkg/cloudprovider/vsphereparavirtual/vmservice/vmservice.go
  pkg/cloudprovider/vsphereparavirtual/vmservice/vmservice_test.go
  pkg/cloudprovider/vsphereparavirtual/zone.go
  pkg/cloudprovider/vsphereparavirtual/zone_test.go
  pkg/util/fake_client_wrapper.go
Labels: cncf-cla: yes, approved, size/XXL, lgtm

#850 fix typo in kubeadm docs
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
Labels: size/XS, cncf-cla: yes, approved, lgtm, ok-to-test

#863 [1.28] Bump Kubernetes golang dependencies from v0.28.0 to v0.28.7
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#862 [1.27] Bump Kubernetes golang dependencies from v0.27.2 to v0.27.11
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#861 [1.26] Bump Kubernetes golang dependencies from v0.26.3 to v0.26.14
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test
