Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2024-03, with the labels that each got.

#876 Add DanielXiao and chenlin as maintainers
  OWNERS_ALIASES
Labels: size/XS, cncf-cla: yes, approved, lgtm

#874 run e2e test suite on latest k8s version
  Makefile
  hack/e2e.sh
  test/e2e/Makefile
  test/e2e/config/vsphere-ci.yaml
  test/e2e/cpi_vm_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
Labels: cncf-cla: yes, size/M, approved, lgtm

#882 add a new github action to auto bump k8s changes
  .github/workflows/bump-k8s.yml
  hack/bump-k8s-dep.sh
Labels: cncf-cla: yes, approved, size/L

#888 Add auto bump action for e2e test
  .github/workflows/bump-k8s-for-e2e-test.yml
  hack/bump-k8s-dep.sh
Labels: cncf-cla: yes, size/M, approved

#892 fix github actions
  .github/workflows/bump-k8s-for-e2e-test.yml
  .github/workflows/bump-k8s.yml
  hack/bump-k8s-dep.sh
Labels: cncf-cla: yes, size/M, approved

#899 improve github actions
  .github/workflows/bump-k8s-for-e2e-test.yml
  .github/workflows/bump-k8s.yml
Labels: cncf-cla: yes, size/M, approved

#903 remove staring docker in make file as suggested to fix cpi post merge job fail because of docker unavailable
  Makefile
Labels: size/XS, cncf-cla: yes, approved, lgtm

#904 fix integration test
  test/integration/Makefile
Labels: size/XS, cncf-cla: yes, approved

#905 run dependabot on three latest release branches
  .github/dependabot.yml
  docs/book/tutorials/make_a_new_cpi_release.md
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#935 [1.28]Cherry pick #904 to fix integration test
  test/integration/Makefile
Labels: size/XS, cncf-cla: yes, approved, lgtm

#936 [1.27]Cherry pick #904 to fix integration test
  test/integration/Makefile
Labels: size/XS, cncf-cla: yes, approved, lgtm

#940 [1.29]Cherry pick #904 to fix integration test
  test/integration/Makefile
Labels: size/XS, cncf-cla: yes, approved

#950 Bump the Kubernetes v0.30.0-beta.0
  cluster/images/controller-manager/Dockerfile
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#957 Support specifying pod IPPool type in VPC network
  pkg/cloudprovider/vsphereparavirtual/cloud.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/core.go
  pkg/cloudprovider/vsphereparavirtual/ippoolmanager/interfaces.go
  pkg/cloudprovider/vsphereparavirtual/ippoolmanager/v1alpha2/ippoolmanager.go
  pkg/cloudprovider/vsphereparavirtual/ippoolmanager/v1alpha2/ippoolmanager_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#958 Fix empty pod ip pool type check
  pkg/cloudprovider/vsphereparavirtual/cloud.go
  pkg/cloudprovider/vsphereparavirtual/config.go
  pkg/cloudprovider/vsphereparavirtual/config_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm
