Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2024-01, with the labels that each got.

#791 Bump latest nsx operator
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#794 Add Yanzhao as maintainer
  OWNERS_ALIASES
Labels: size/XS, cncf-cla: yes, approved, lgtm

#793 [Fix]Monitor the path of supervisor config and restart if it's updated
  cmd/vsphere-cloud-controller-manager/main.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#798 Fix the fs watcher to only watch ccm-provider if it's paravirtual
  cmd/vsphere-cloud-controller-manager/main.go
Labels: size/XS, cncf-cla: yes, approved, lgtm

#795 Add dependabot so package could be bumped automatically
  .github/dependabot.yml
Labels: cncf-cla: yes, size/M, approved, lgtm

#796 Bump golang version in go.mod to go 1.21
  cluster/images/controller-manager/Dockerfile
  go.mod
  go.sum
  hack/images/ci/Dockerfile
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#810 Bump Kubernetes 1.29
  cluster/images/controller-manager/Dockerfile
  go.mod
  go.sum
  pkg/cloudprovider/vsphere/cloud.go
  pkg/cloudprovider/vsphere/nodemanager.go
  pkg/cloudprovider/vsphereparavirtual/controllers/routablepod/ippool/ippool_controller.go
  pkg/cloudprovider/vsphereparavirtual/ippoolmanager/v1alpha1/ippoolmanager.go
  pkg/cloudprovider/vsphereparavirtual/ippoolmanager/v1alpha2/ippoolmanager.go
  pkg/cloudprovider/vsphereparavirtual/route.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, approved, size/XXL, lgtm, ok-to-test

#807 Improve logs collection in e2e testing
  hack/e2e.sh
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, size/XL, approved, lgtm, ok-to-test

#809 Cleanup VSphere sessions on SIGTERM
  cmd/vsphere-cloud-controller-manager/main.go
  pkg/cloudprovider/vsphere/cloud.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#820 Release 1.29.0 helm charts
  charts/vsphere-cpi-1.29.0.tgz
  index.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#821 Release 1.29.0 helm charts
  charts/vsphere-cpi-1.29.0.tgz
  index.yaml
Labels: cncf-cla: yes, approved, size/S

#822 Fix index error in v1.29.0 helm charts
  charts/vsphere-cpi-1.29.0.tgz
  index.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#823 Fix index error in v1.29.0 helm charts
  charts/vsphere-cpi-1.29.0.tgz
  index.yaml
Labels: cncf-cla: yes, approved, size/S

#824 Add more doc about how to cut a release
  docs/book/tutorials/make_a_new_cpi_release.md
Labels: size/XS, cncf-cla: yes, approved, lgtm

#825 Use openvpn from community-owned registry
  hack/e2e.sh
Labels: size/XS, cncf-cla: yes, approved, lgtm

#828 Use K8s v1.29.0 in e2e test
  test/e2e/Makefile
  test/e2e/config/vsphere-ci.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test
