Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2024-11, with the labels that each got.

#1288 Release 1.30.2
  README.md
  charts/vsphere-cpi-1.30.2.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/README.md
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/disable-node-deletion.yaml
  docs/book/tutorials/kubernetes-on-vsphere-with-kubeadm.md
  index.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
  releases/README.md
  releases/v1.30/vsphere-cloud-controller-manager.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#1287 Release 1.31.1
  README.md
  charts/vsphere-cpi-1.31.1.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/README.md
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/disable-node-deletion.yaml
  index.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
  releases/README.md
  releases/v1.31/vsphere-cloud-controller-manager.yaml
  test/e2e/config/vsphere-ci.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#1289 Release 1.29.2
  charts/vsphere-cpi-1.29.2.tgz
  charts/vsphere-cpi/Chart.yaml
  charts/vsphere-cpi/README.md
  charts/vsphere-cpi/values.yaml
  cluster/images/controller-manager/Dockerfile
  docs/book/tutorials/disable-node-deletion.yaml
  index.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml
  manifests/controller-manager/vsphere-cloud-controller-manager-pod.yaml
  releases/README.md
  releases/v1.29/vsphere-cloud-controller-manager.yaml
  test/e2e/config/vsphere-ci.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#1282 🧑‍🤝‍🧑 add gong and danqing as cloud provider vsphere maintainer
  OWNERS_ALIASES
Labels: size/XS, cncf-cla: yes, approved, lgtm

#1298 🌱 Bump the Kubernetes group to v0.32.0-beta.0
  cluster/images/controller-manager/Dockerfile
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#1299 Add permission for the GitHub actions
  .github/workflows/auto-release-helm-chart.yml
  .github/workflows/bump-k8s-dep.yml
  .github/workflows/bump-test-k8s-dep.yml
Labels: cncf-cla: yes, approved, size/S, lgtm

#1300 [Cherry-Pick] Add permission for the GitHub actions
  .github/workflows/auto-release-helm-chart.yml
  .github/workflows/bump-k8s-dep.yml
  .github/workflows/bump-test-k8s-dep.yml
Labels: cncf-cla: yes, approved, size/S, lgtm

#1301 Update helm repo index for 1.31.1
  index.yaml
Labels: cncf-cla: yes, size/S, lgtm

#1303 Bump govmomi to v0.45.1
  go.mod
  go.sum
Labels: size/XS, cncf-cla: yes, approved, lgtm

#1318 Fix generate release notes error
  .github/workflows/generate-release-notes.yml
Labels: size/XS, cncf-cla: yes, approved, lgtm

#1319 Fix the stale Node issue in cache
  hack/tools/go.mod
  pkg/cloudprovider/vsphereparavirtual/cloud.go
  pkg/cloudprovider/vsphereparavirtual/route.go
  pkg/cloudprovider/vsphereparavirtual/route_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm
