Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2025-06, with the labels that each got.

#1502 e2e: adjustments to enable e2e on community prow
  hack/e2e.sh
  test/e2e/config/vsphere-ci.yaml
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#1504 [release-1.32] Cherry-pick: adjustments to enable e2e on community prow
  hack/e2e.sh
  test/e2e/config/vsphere-ci.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#1505 [release-1.31] cherry-pick: adjustments to enable e2e on community prow
  hack/e2e.sh
  test/e2e/config/vsphere-ci.yaml
Labels: cncf-cla: yes, size/M

#1507 fix: change RoleBinding namespace to kube-system
  charts/vsphere-cpi/templates/role-binding.yaml
Labels: size/XS, cncf-cla: yes, approved, lgtm, ok-to-test
