Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2025-05, with the labels that each got.

#1482 Bump CAPI to v1.10.1 & CAPV to 1.13.0 in E2E
  test/e2e/Makefile
  test/e2e/config/vsphere-ci.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: do-not-merge/hold, cncf-cla: yes, size/M, approved, lgtm

#1478 Update dependabot for 1.33 release
  .github/dependabot.yml
Labels: cncf-cla: yes, size/M, approved, lgtm

#1496 🌱 Enable weekly security check job
  .github/workflows/weekly-security-scan.yaml
  Makefile
  hack/ensure-trivy.sh
  hack/go-install.sh
  hack/verify-container-images.sh
Labels: cncf-cla: yes, approved, size/L, lgtm

#1489 Implement shared session capability
  docs/book/vc_shared_sessions.md
  pkg/common/connectionmanager/connectionmanager.go
  pkg/common/connectionmanager/zones.go
  pkg/common/credentialmanager/credentialmanager.go
  pkg/common/credentialmanager/credentialmanager_test.go
  pkg/common/credentialmanager/types.go
  pkg/common/vclib/connection.go
  pkg/common/vclib/vc_session_manager.go
  pkg/common/vclib/vc_session_manager_test.go
Labels: cncf-cla: yes, size/XL, approved, lgtm
