Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2025-07, with the labels that each got.

#1514 Update Supervisor API calls to use FQDN
  pkg/cloudprovider/vsphereparavirtual/config.go
  pkg/cloudprovider/vsphereparavirtual/config_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#1530 🌱 Bump the Kubernetes group to v0.34.0-beta.0
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#1526 🌱 Bump CAPI alpha&CAPV alpha&Controller Runtime in E2E
  test/e2e/Makefile
  test/e2e/config/vsphere-ci.yaml
  test/e2e/cpi_vm_test.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, approved, size/L

#1531 🌱 Bump CAPI v1.11.0-beta.0 & CAPV v1.14.0-beta.0 in E2E
  test/e2e/Makefile
  test/e2e/config/vsphere-ci.yaml
  test/e2e/cpi_vm_test.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#1541 🌱 Automate image promotion
  Makefile
Labels: cncf-cla: yes, approved, size/S, lgtm

#1546 Fix security scan
  .github/workflows/weekly-security-scan.yaml
Labels: size/XS, cncf-cla: yes, approved
