Repository kubernetes/cloud-provider-vsphere, pull requests merged in 2025-04, with the labels that each got.

#1464 Bump e2e to use latest CAPI/CAPV and refine testcases
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/Makefile
  test/e2e/config/vsphere-ci.yaml
  test/e2e/cpi_vm_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/vsphere.go
Labels: cncf-cla: yes, size/XL, approved, lgtm

#1476 🌱 Bump e2e to use latest CAPI/CAPV
  test/e2e/Makefile
  test/e2e/config/vsphere-ci.yaml
  test/e2e/go.mod
  test/e2e/go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#1474  🌱 Bump the Kubernetes group to v0.33.0
  go.mod
  go.sum
Labels: do-not-merge/hold, cncf-cla: yes, size/M, approved, lgtm

#1322 Added the ability to apply extra volumes, volume mounts and host aliases to the daemonset
  charts/vsphere-cpi/README.md
  charts/vsphere-cpi/templates/configmap.yaml
  charts/vsphere-cpi/templates/daemonset.yaml
  charts/vsphere-cpi/values.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test
